# Preface {.unnumbered}


## Websites, PDF version of the book, and R code from the book

The book is available at these two websites.


[https://mwalkerstatistics.com](https://mwalkerstatistics.com) 

This website has a free PDF version of the book. It also has all the R code in the book in an R script file that you can download.

[https://stats001.github.io/pvalues/](https://stats001.github.io/pvalues/)

This website is the github repository for the book. 

On the website, click here for the free PDF version of the book: 

[Download the PDF version of the book](downloads/How-to-Get-P-Values-Less-Than-0.05-in-Biological-Research.pdf)

On the website, click here for the R code in the book in an R script file that you can download:

[Download the R code from the book](downloads/P_Values_Book_R_Code.R)

The book will also be available through Amazon Kindle, in Kindle Unlimited.


## A note on what this book is and isn't

The title of this book is deliberately provocative, and I want to be direct about what it means and what it doesn't. Every method described here is about choosing the most appropriate, most powerful statistical analysis for your data and your experimental design. These are decisions you make before you look at your results. None of them are about running analysis after analysis until one happens to cross the p < 0.05 line, then reporting only that one. That practice has a name: data dredging, or “p-hacking.” It produces false positives, wastes other scientists’ time trying to replicate effects that were never real, and is a problem I take seriously enough to devote two full chapters to later in this book (see “The wrong way and the right way to get p < 0.05” and “Is p < 0.05 the right goal?”).

## Companion book: A Gentle Introduction to Statistics for Biological Research

In *A Gentle Introduction to Statistics for Biological Research*, I introduce and explain the methods that I recommend in *How to Get P-Values Less Than 0.05 in Biological Research*.

The website [mwalkerstatistics.com](https://mwalkerstatistics.com) has a free PDF version of the companion book.

If you have no experience with statistics, I suggest that you start with the companion book. If you have some exposure to statistics, including standard deviation and t-tests, you can begin reading *How to Get P-Values Less Than 0.05 …*, and refer to *A Gentle Introduction …* when you need or would like more explanation of a particular concept or method.

## R packages used in the book

These are R packages used in the examples. It may save some time if you install these now.

install.packages(c("ggplot2", "Rfit", "RobStatTM", "car", "vcdExtra", "tibble", "dplyr", "tidyverse", "survival", "survminer", "coin", "rankFD"))

## Dedication {.unnumbered}

*To Kai Kai, with hope that biological research will make the world a better place for her and all children. To my family for their love and support.*

## Acknowledgements {.unnumbered}

Thank you to my teachers and advisors, who encouraged exploration and showed their own love of science and learning. Thank you to my colleagues and students who have asked the questions that made me think about and better understand statistics. Thank you to my family for supporting this work over many years. Thank you to the reviewers who have made this book better. Whatever is good in this book has come from these friends and colleagues. The errors, of course, are my responsibility, and show that I still have things to learn.

## About the author {.unnumbered}

Michael Walker received his Ph.D. from Stanford University and taught statistics and clinical trial design at Stanford and UC San Diego for 25 years. He is a statistics consultant for pharmaceutical and biotechnology companies. His consulting work has led to FDA approval for new drugs, medical devices, and diagnostic tests. He has published in the New England Journal of Medicine and in Lancet, among over 70 publications. He provides statistics consulting for venture capital companies to evaluate investments in life sciences.

## Copyright {.unnumbered}

Copyright © 2026 by Michael G. Walker

All rights reserved. No portion of this book may be reproduced in any form without written permission from the author, except as permitted by U.S. copyright law.

*Limitation of liability and disclaimer of warranty.* This publication is intended for educational purposes. It is designed to provide accurate information in regard to the subject matter covered. However, this book is not an exhaustive treatment of the subjects. The advice and strategies contained herein may not be suitable for your situation. You should consult a professional for your specific statistical questions and needs, or when otherwise appropriate. While the author has used best efforts in preparing this book, he makes no representations or warranties with respect to the accuracy or completeness of the contents of this book and specifically disclaims any implied warranties of merchantability or fitness for a particular purpose. No liability is assumed for losses or damages due to the information provided.
