<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Practical examples of how to increase power, reduce sample size, and choose better statistics tests">

<title>6&nbsp; If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables – How to Get P-Values Less Than 0.05 in Biological Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch07-survival-analysis.html" rel="next">
<link href="../chapters/ch05-rank-one-predictor.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-24cd44e0416da4fd58bb0517b27b0746.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-21613c26995e5ad49e067cca7f3a46fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-24cd44e0416da4fd58bb0517b27b0746.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ch06-rank-more-than-one-predictor.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">How to Get P-Values Less Than 0.05 in Biological Research</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Stats001/pvalues" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-avoid-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Avoid t-tests: Control for variables using multiple regression or ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-power-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Calculate power and sample size if you want p &lt; 0.05</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-reduce-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Increase sample size last: reduce unexplained variability first</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-robust-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">If you have normally distributed data with outliers: Robust tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-rank-one-predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">If you have non-normal data and one explanatory variable: Wilcoxon and Kruskal-Wallis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-rank-more-than-one-predictor.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">For count outcomes consider negative binomial regression and Wilcoxon tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-avoid-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Avoid turning quantitative variables into categorical variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-cmh-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Avoid Chi-Squared tests when you have ordered categories: use CMH tests instead</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-balancing-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Balancing variables across treatment groups is not sufficient to get best p-values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-correlated-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Avoid correlated explanatory variables in multiple regression and ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Look (out) for interactions: when subgroups respond differently to treatment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-two-primary-analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Use two primary analyses each with alpha 0.025 instead of one with 0.05</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-avoid-OVAT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Avoid one-variable-at-a-time experiments. Use factorial experiment design.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-rescue-factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Rescue failed experiments using fractional factorial designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The wrong way and the right way to get p &lt; 0.05: multiple hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-right-goal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Is P &lt; 0.05 the right goal?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-p-greater-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">What if you still get p &gt; 0.05?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-claude-for-these-analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Don’t know R? Use Claude to run these analyses for you</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview-of-rank-methods-for-multiple-explanatory-variables" id="toc-overview-of-rank-methods-for-multiple-explanatory-variables" class="nav-link active" data-scroll-target="#overview-of-rank-methods-for-multiple-explanatory-variables"><span class="header-section-number">6.1</span> Overview of rank methods for multiple explanatory variables</a>
  <ul class="collapse">
  <li><a href="#van-elteren-stratified-wilcoxon-test-with-coin" id="toc-van-elteren-stratified-wilcoxon-test-with-coin" class="nav-link" data-scroll-target="#van-elteren-stratified-wilcoxon-test-with-coin">Van Elteren stratified Wilcoxon test with coin</a></li>
  <li><a href="#rank-based-regression-with-rfit" id="toc-rank-based-regression-with-rfit" class="nav-link" data-scroll-target="#rank-based-regression-with-rfit">Rank-based regression with Rfit</a></li>
  <li><a href="#rankfd-for-rank-based-analysis-of-variance-and-factorial-design" id="toc-rankfd-for-rank-based-analysis-of-variance-and-factorial-design" class="nav-link" data-scroll-target="#rankfd-for-rank-based-analysis-of-variance-and-factorial-design">rankFD for Rank-based analysis of variance and factorial design</a></li>
  </ul></li>
  <li><a href="#example-data-set-with-outliers" id="toc-example-data-set-with-outliers" class="nav-link" data-scroll-target="#example-data-set-with-outliers"><span class="header-section-number">6.2</span> Example data set with outliers</a></li>
  <li><a href="#analysis-using-standard-anova" id="toc-analysis-using-standard-anova" class="nav-link" data-scroll-target="#analysis-using-standard-anova"><span class="header-section-number">6.3</span> Analysis using standard anova</a></li>
  <li><a href="#rank-based-analysis-using-the-van-elteren-stratified-wilcoxon-test" id="toc-rank-based-analysis-using-the-van-elteren-stratified-wilcoxon-test" class="nav-link" data-scroll-target="#rank-based-analysis-using-the-van-elteren-stratified-wilcoxon-test"><span class="header-section-number">6.4</span> Rank-based analysis using the van Elteren stratified Wilcoxon test</a></li>
  <li><a href="#rank-based-analysis-using-the-rfit-package" id="toc-rank-based-analysis-using-the-rfit-package" class="nav-link" data-scroll-target="#rank-based-analysis-using-the-rfit-package"><span class="header-section-number">6.5</span> Rank-based analysis using the Rfit package</a></li>
  <li><a href="#compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-data-with-outliers" id="toc-compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-data-with-outliers" class="nav-link" data-scroll-target="#compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-data-with-outliers"><span class="header-section-number">6.6</span> Compare power for Wilcoxon, stratified Wilcoxon and rfit: data with outliers</a></li>
  <li><a href="#compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-no-outliers" id="toc-compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-no-outliers" class="nav-link" data-scroll-target="#compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-no-outliers"><span class="header-section-number">6.7</span> Compare power for Wilcoxon, stratified Wilcoxon and rfit: no outliers</a></li>
  <li><a href="#limitations-of-the-rank-methods" id="toc-limitations-of-the-rank-methods" class="nav-link" data-scroll-target="#limitations-of-the-rank-methods"><span class="header-section-number">6.8</span> Limitations of the rank methods</a>
  <ul class="collapse">
  <li><a href="#limitations-of-the-van-elteren-stratified-wilcoxon-test" id="toc-limitations-of-the-van-elteren-stratified-wilcoxon-test" class="nav-link" data-scroll-target="#limitations-of-the-van-elteren-stratified-wilcoxon-test">Limitations of the van Elteren stratified Wilcoxon test</a></li>
  <li><a href="#limitations-of-rfit" id="toc-limitations-of-rfit" class="nav-link" data-scroll-target="#limitations-of-rfit">Limitations of Rfit</a></li>
  </ul></li>
  <li><a href="#appendix-how-does-rfit-rank-regression-work" id="toc-appendix-how-does-rfit-rank-regression-work" class="nav-link" data-scroll-target="#appendix-how-does-rfit-rank-regression-work"><span class="header-section-number">6.9</span> Appendix: How does Rfit rank regression work?</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Stats001/pvalues/edit/main/chapters/ch06-rank-more-than-one-predictor.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Stats001/pvalues/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Data that are not normally distributed can cause loss of power and poor p-values for t-test, analysis of variance and multiple regression. The Wilcoxon rank sum test and Kruskal-Wallis help if you only have one explanatory variable, but what if you have more than one variable that affects the outcome? In this chapter we’ll look at rank methods that allow for multiple explanatory variables.</p>
<p>Load these libraries to run the examples in this chapter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(coin)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rfit)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rankFD)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="overview-of-rank-methods-for-multiple-explanatory-variables" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="overview-of-rank-methods-for-multiple-explanatory-variables"><span class="header-section-number">6.1</span> Overview of rank methods for multiple explanatory variables</h2>
<p>Rank analysis is an active area of statistics research. Several R packages and tools are available. We’ll focus on these two:</p>
<ul>
<li><p>Van Elteren stratified Wilcoxon test (coin package)</p></li>
<li><p>Rank-based regression (Rfit package)</p></li>
</ul>
<section id="van-elteren-stratified-wilcoxon-test-with-coin" class="level3">
<h3 class="anchored" data-anchor-id="van-elteren-stratified-wilcoxon-test-with-coin">Van Elteren stratified Wilcoxon test with coin</h3>
<p>The van Elteren stratified Wilcoxon test was first published in 1960. Among its advantages are the facts that it is fairly widely known and has been used for FDA submissions and in articles published in the major medical and scientific journals. It has some disadvantages that we’ll note shortly. It is available in standard statistics packages such as SAS and R. We’ll use the van Elteren test from the R package coin.</p>
</section>
<section id="rank-based-regression-with-rfit" class="level3">
<h3 class="anchored" data-anchor-id="rank-based-regression-with-rfit">Rank-based regression with Rfit</h3>
<p>Rfit is built around rank-based regression as an alternative to ordinary least squares regression. The Rfit package accompanies the textbook “Nonparametric Statistical Methods Using R” by John Kloke and Joseph W. McKean <span class="citation" data-cites="kloke2015">(<a href="references.html#ref-kloke2015" role="doc-biblioref">J. Kloke and McKean 2015</a>)</span>. Think of it as a rank-based alternative to lm(). The appendix to this chapter gives a brief comparison of rfit versus traditional least-squares regression.</p>
</section>
<section id="rankfd-for-rank-based-analysis-of-variance-and-factorial-design" class="level3">
<h3 class="anchored" data-anchor-id="rankfd-for-rank-based-analysis-of-variance-and-factorial-design">rankFD for Rank-based analysis of variance and factorial design</h3>
<p>The rankFD package accompanies the textbook “Rank and Pseudo-Rank Procedures for Independent Observations in Factorial Designs” by Brunner <span class="citation" data-cites="brunner2018">(<a href="references.html#ref-brunner2018" role="doc-biblioref">Brunner et al. 2018</a>)</span>.</p>
<p>rankFD is built around nonparametric hypothesis testing in factorial designs. It is particulalry useful if you are looking for a rank-based alternative for factorial analysis of variance and experiment design.</p>
</section>
</section>
<section id="example-data-set-with-outliers" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="example-data-set-with-outliers"><span class="header-section-number">6.2</span> Example data set with outliers</h2>
<p>We’ll use this anova.2way.data.outlier data set for some of the examples.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier <span class="ot">=</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="sc">~</span>Treatment, <span class="sc">~</span>Litter, <span class="sc">~</span>Response,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">4</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">8</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">11</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">12</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">13</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">15</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">20</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">32</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">10</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">15</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">16</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">17</span>,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">19</span>,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">20</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">31</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co"># van Elteren stratified Wilcoxon test from the coin R package  </span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># requires that covariates are defined to be factors</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Litter <span class="ot">=</span> <span class="fu">as.factor</span>(anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Litter)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Treatment <span class="ot">=</span> <span class="fu">as.factor</span>(anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Treatment)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(anova<span class="fl">.2</span>way.data.outlier)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [16 × 3] (S3: tbl_df/tbl/data.frame)
 $ Treatment: Factor w/ 2 levels "Drug","Placebo": 1 1 1 1 1 1 1 1 2 2 ...
 $ Litter   : Factor w/ 4 levels "Litter.1","Litter.2",..: 1 1 2 2 3 3 4 4 1 1 ...
 $ Response : num [1:16] 4 8 11 12 13 15 20 32 10 15 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(anova<span class="fl">.2</span>way.data.outlier, <span class="fu">aes</span>(<span class="at">y=</span>Response, <span class="at">x=</span>Treatment)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Litter) <span class="sc">+</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtitle</span>(<span class="st">"Response to treatment  </span><span class="sc">\n</span><span class="st">broken out by Litter, with outliers"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch06-rank-more-than-one-predictor_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The outliers in litter 4 are evident, as is the large difference in response between the litters.</p>
</section>
<section id="analysis-using-standard-anova" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="analysis-using-standard-anova"><span class="header-section-number">6.3</span> Analysis using standard anova</h2>
<p>Start with an ordinary two-way ANOVA for this data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.2</span>way.outlier <span class="ot">=</span> <span class="fu">lm</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span> anova<span class="fl">.2</span>way.data.outlier)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm<span class="fl">.2</span>way.outlier)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: Response
          Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Litter     3 596.50 198.833 12.7718 0.0006627 ***
Treatment  1  72.25  72.250  4.6409 0.0542426 .  
Residuals 11 171.25  15.568                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The ordinary two-way ANOVA confirms the additional variability due to litter (p = 0.00066) but treatment is not significant (p = 0.054).</p>
</section>
<section id="rank-based-analysis-using-the-van-elteren-stratified-wilcoxon-test" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="rank-based-analysis-using-the-van-elteren-stratified-wilcoxon-test"><span class="header-section-number">6.4</span> Rank-based analysis using the van Elteren stratified Wilcoxon test</h2>
<p>The syntax for the van Elteren stratified Wilcoxon test is to specify the usual formula “Response ~ Treatment” followed by a vertical bar “|” and the stratification variable, in this case “Litter”. As the code below shows, this gives “Response ~ Treatment | Litter”. Note also that the van Elteren stratified Wilcoxon test from the R package coin requires that the explanatory variables are defined to be factors.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># van Elteren stratified Wilcoxon test</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox_test</span>(Response <span class="sc">~</span> Treatment <span class="sc">|</span> Litter,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data         =</span> anova<span class="fl">.2</span>way.data.outlier,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distribution =</span> <span class="st">"asymptotic"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Asymptotic Wilcoxon-Mann-Whitney Test

data:  Response by
     Treatment (Drug, Placebo) 
     stratified by Litter
Z = -2.636, p-value = 0.00839
alternative hypothesis: true mu is not equal to 0</code></pre>
</div>
</div>
<p>The van Elteren stratified Wilcoxon test gives p = 0.008 for treatment, stratifying for Litter, which is an improvement over the non-significant result for the two-way anova.</p>
<p>Watch out for errors in the formula syntax for the stratified Wilcoxon test using wilcox_test. An easy mistake to make (I know, because I’ve done it) is formatting a stratified test as Response ~ Treatment + Litter. The stratified Wilcoxon using wilcox_test from the coin package must be formatted with a vertical bar indicating the blocking variable: Response ~ Treatment | Litter.</p>
</section>
<section id="rank-based-analysis-using-the-rfit-package" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="rank-based-analysis-using-the-rfit-package"><span class="header-section-number">6.5</span> Rank-based analysis using the Rfit package</h2>
<p>Another alternative for rank-based analysis is the Rfit package. To run these examples, install and load the package with this code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("Rfit") # if not already installed</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rfit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Here is the analysis of the outlier data, with litter and treatment as the two explanatory variables. The function rfit() performs the analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier.rfit <span class="ot">=</span> <span class="fu">with</span>(anova<span class="fl">.2</span>way.data.outlier,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rfit</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment))</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova<span class="fl">.2</span>way.data.outlier.rfit)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rfit.default(formula = Response ~ Litter + Treatment)

Coefficients:
                 Estimate Std. Error t.value   p.value    
(Intercept)        7.2500     2.0287  3.5737  0.004366 ** 
LitterLitter.2     4.2500     2.5213  1.6857  0.119987    
LitterLitter.3     7.2500     2.5213  2.8755  0.015092 *  
LitterLitter.4    16.0000     2.5213  6.3460 5.475e-05 ***
TreatmentPlacebo   5.0000     1.7828  2.8046  0.017135 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Multiple R-squared (Robust): 0.7677992 
Reduction in Dispersion Test: 9.0932 p-value: 0.0017 </code></pre>
</div>
</div>
<p>The rank-based rfit test indicates that treatment has a significant effect (p = 0.017). Compare this result to the conventional two-way ANOVA result of p = 0.054, which indicated that treatment was not significant.</p>
<p>The output also indicates that there are significant differences among the litters.</p>
<p>We could have started the analysis with an interaction test, using the Rfit function raov. The formula “Response ~ Litter * Treatment” specifies the interaction test.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(anova<span class="fl">.2</span>way.data.outlier, <span class="fu">raov</span>(Response <span class="sc">~</span> Litter <span class="sc">*</span> Treatment))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Robust ANOVA Table
                 DF       RD  Mean RD       F p-value
Litter            3 55.90170 18.63390 6.69423 0.01423
Treatment         1  7.37902  7.37902 2.65092 0.14214
Litter:Treatment  3  1.11803  0.37268 0.13388 0.93711</code></pre>
</div>
</div>
<p>The interaction test is not significant (p = 0.937), indicating that there is no interaction between treatment and litter. So, the model without interaction was suitable.</p>
<p>We can also examine the results for rfit for the data with no outliers.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data <span class="ot">=</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="sc">~</span>Treatment, <span class="sc">~</span>Litter, <span class="sc">~</span>Response,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">4</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">8</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">11</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">12</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">13</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">15</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">20</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">10</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">15</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">16</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">17</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">19</span>,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">20</span>,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">23</span></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">rfit</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment, <span class="at">data =</span> anova<span class="fl">.2</span>way.data))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
rfit.default(formula = Response ~ Litter + Treatment, data = anova.2way.data)

Coefficients:
                 Estimate Std. Error t.value   p.value    
(Intercept)        7.2500     1.4574  4.9746  0.000419 ***
LitterLitter.2     4.5000     1.7165  2.6216  0.023761 *  
LitterLitter.3     7.5000     1.7165  4.3693  0.001119 ** 
LitterLitter.4    12.0000     1.7165  6.9909 2.297e-05 ***
TreatmentPlacebo   4.5000     1.2138  3.7075  0.003456 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Multiple R-squared (Robust): 0.8141111 
Reduction in Dispersion Test: 12.04378 p-value: 0.00052 </code></pre>
</div>
</div>
<p>We see that, for the data with no outliers, the p-value for the rfit method (p = 0.003456) is similar to the p-value for the classical analysis of variance (p = 0.000545), although not quite so good.</p>
</section>
<section id="compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-data-with-outliers" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-data-with-outliers"><span class="header-section-number">6.6</span> Compare power for Wilcoxon, stratified Wilcoxon and rfit: data with outliers</h2>
<p>Let’s run some simulations to compare power for these rank methods. We’ll start with a data set that has outliers. Code for the simulations is on the book website.</p>
<p>For this first simulation, we’ll assume the following.</p>
<ul>
<li>Two group: “Control” and “Treatment”</li>
<li>Response (y) variable is “Outcome”</li>
<li>Study is performed at 9 sites. Sites are a source of variation.</li>
<li>The number of observations per site in each group is 4, 6 or 8.</li>
<li>Within each site, within each treatment group, data is randomly sampled from a normal distribution (mean = 20, sd = 4), with the addition of 2 outliers each to the “Control” and “Treatment” groups within each site.</li>
<li>Within site the Treatment group is shifted relative to the Control group. We use a range of shift values from 1 to 5 by 0.5</li>
</ul>
<p>The graph below shows the data for one simulation. Notice both the differences among the sites and the differences between treatment groups within each site.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figures/rank_power_sim_w_outliers.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The graph below shows the power curves comparing the analysis methods over many simulations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figures/rank_sim_power_curves_w_outliers.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>For this simulated data set with an important covariate (site) and outliers, the methods that ignore the covariate (t-test and Wilcoxon rank sum) have the lowest power. The linear model that adjusts for the site covariate has more power, but lower power than the stratified Wilcoxon and rfit, both of which adjust for the site covariate and handle the outliers without inflating the variance.</p>
<p>How does the power compare for data without outliers? We’ll look at that next.</p>
</section>
<section id="compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-no-outliers" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="compare-power-for-wilcoxon-stratified-wilcoxon-and-rfit-no-outliers"><span class="header-section-number">6.7</span> Compare power for Wilcoxon, stratified Wilcoxon and rfit: no outliers</h2>
<p>Now we’ll compare the power for the 5 methods for data with no outliers. The data is the same as for the simulation above, except that no outliers are added.</p>
<p>The graph below shows the data for one simulation. Notice both the differences among the sites and the differences between treatment groups within each site.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figures/rank_power_sim_no_outliers.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>The graph below shows the power curves comparing the analysis methods over many simulations.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="figures/rank_sim_power_curves_no_outliers.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>For this simulated data set with an important covariate (site) but no outliers, the two methods that ignore the site covariate (linear model with no site adjustment and Wilcoxon rank sum) have the lowest power. The stratified Wilcoxon, rfit, and linear model that adjust for the site covariate all have similar power. For data that are normally distributed with no outliers, rfit is expected to have 95% of the power of the linear model. So the results seen here are not surprising.</p>
</section>
<section id="limitations-of-the-rank-methods" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="limitations-of-the-rank-methods"><span class="header-section-number">6.8</span> Limitations of the rank methods</h2>
<p>Every method (including t-tests, anova, and linear regression) has assumptions and limitations. Here we note limitations of the rank methods considered in this chapter.</p>
<section id="limitations-of-the-van-elteren-stratified-wilcoxon-test" class="level3">
<h3 class="anchored" data-anchor-id="limitations-of-the-van-elteren-stratified-wilcoxon-test">Limitations of the van Elteren stratified Wilcoxon test</h3>
<p>The van Elteren test (1960) is a stratified extension of the Wilcoxon–Mann–Whitney rank-sum test. It combines within-stratum rank statistics into a single weighted statistic, controlling one or more stratification factors. While useful, the procedure carries several important limitations. These are described in some detail in the textbook by Brunner <span class="citation" data-cites="brunner2018">(<a href="references.html#ref-brunner2018" role="doc-biblioref">Brunner et al. 2018</a>)</span>.</p>
<p><strong>Assumes uniform effect cross strata</strong></p>
<p>The test combines stratum-level rank statistics by weighting them, implicitly assuming a common treatment effect across all strata. If the true effect varies considerably from stratum to stratum (there is a treatment-by-stratum interaction), the single combined p-value can be misleading. It is a good idea to look at the within-stratum results before relying solely on the overall test.</p>
<p><strong>Reduced power with many small strata</strong></p>
<p>When the number of strata is large relative to the total sample size, so that many strata contain only a handful of observations, the within-stratum rank information becomes very sparse. The test can lose power compared to an unstratified Wilcoxon test, or even compared to a parametric approach such as a mixed model. A common guideline is to avoid strata with fewer than five observations per treatment arm.</p>
<p><strong>Ties require careful handling</strong></p>
<p>Like all rank-based methods, the van Elteren test requires an adjustment when tied observations are present. Standard mid-rank tie-breaking is incorporated into the usual variance formula, but with heavy ties (for example, an ordinal outcome with only a few levels) the normal approximation to the null distribution can be poor, inflating the Type I error rate. In such cases a permutation or exact version of the test should be considered.</p>
<p><strong>No built-in effect size estimate</strong></p>
<p>The test produces a p-value, but it does not directly provide an effect-size estimate or confidence interval. To quantify the magnitude of the treatment difference, a companion measure such as the stratified Hodges–Lehmann location shift must be computed separately. Reporting a p-value alone may be insufficient for clinical or scientific interpretation.</p>
<p><strong>Asymptotic validity requires adequate sample size</strong></p>
<p>The standard test relies on a large-sample normal approximation. With very small per-stratum sample sizes the approximation may be unreliable. Exact conditional permutation tests are available but are computationally intensive, and software implementations vary in whether they offer this option.</p>
<p><strong>Sensitive to stratum definition</strong></p>
<p>The stratification scheme should be defined before the analysis and should reflect genuine a priori prognostic factors. Post-hoc choice of strata or collapsing / splitting strata after seeing the data inflates the Type I error. Regulatory guidance (such as ICH E9) requires pre-specification of the stratification factors in the statistical analysis plan.</p>
<p><strong>Practical guidance</strong></p>
<p>None of these limitations invalidates the van Elteren test. It remains a widely-used, nonparametric option for stratified two-group comparisons in clinical trials and observational studies. The key safeguards are to pre-specify the stratification factors and weighting scheme, verify the homogeneity-of-effect assumption, ensure strata are not too small, and supplement the p-value with a suitable effect-size estimate and confidence interval.</p>
</section>
<section id="limitations-of-rfit" class="level3">
<h3 class="anchored" data-anchor-id="limitations-of-rfit">Limitations of Rfit</h3>
<p>The rfit package <span class="citation" data-cites="kloke2012">(<a href="references.html#ref-kloke2012" role="doc-biblioref">J. D. Kloke and McKean 2012</a>)</span> implements rank-based estimation and inference for linear models in R. It fits regression coefficients by minimizing a rank-based dispersion function derived from Jaeckel <span class="citation" data-cites="jaeckel1972">(<a href="references.html#ref-jaeckel1972" role="doc-biblioref">Jaeckel 1972</a>)</span>, producing estimates that are robust to non-normality and heavy-tailed errors while retaining high efficiency relative to ordinary least squares. Despite these advantages, the approach has a number of limitations that practitioners should understand before adopting it as a primary analytical strategy.</p>
<p><strong>Relies on asymptotic theory. May be inaccurate with small samples.</strong></p>
<p>The standard errors, t-statistics, and F-statistics produced by rfit are justified by large-sample asymptotic arguments. In small datasets the normal and chi-squared approximations underpinning these quantities can be unreliable, leading to poorly calibrated p-values and confidence intervals.</p>
<p><strong>Choice of score function can affect results</strong></p>
<p>The method requires selection of a score function (e.g., Wilcoxon, sign, normal, Bent scores) that determines what distributional shape is being targeted. The default Wilcoxon scores are optimal when the error distribution is logistic. Choosing an inappropriate score function can reduce efficiency relative to least squares or relative to the correctly specified rank estimator.</p>
<p><strong>Estimates are location shift, not conditional means</strong></p>
<p>Rank-based regression via rfit estimates shift parameters in a location model rather than conditional means. Location shift as an effect descriptor is less familiar to many users than effect sizes based on means.</p>
<p><strong>Ties in the outcome degrade performance</strong></p>
<p>Like all rank-based methods, rfit uses mid-rank tie-breaking by default. When the outcome contains many ties, as is common with ordinal scales, rounded measurements, or clumped continuous data, the dispersion function becomes less sensitive to differences among tied values and efficiency is reduced</p>
<p><strong>Limited availability and regulatory acceptance</strong></p>
<p>The Rfit package (Kloke &amp; McKean, 2012) is available in R but has no direct equivalent in SAS, Stata, or Python. Moreover, rank-based linear regression has little presence in FDA or EMA guidance documents, so its use as a primary analysis in confirmatory clinical trials requires additional scientific justification compared with OLS or prespecified nonparametric alternatives.</p>
<p><strong>Practical guidance</strong></p>
<p>Rfit is best suited to continuous, approximately symmetric outcomes in moderately large samples where robustness to heavy tails or outliers in the response is the primary concern. For small samples, sparse or ordinal outcomes, or settings requiring regulatory acceptance, alternative approaches should be considered alongside or instead of rfit.</p>
</section>
</section>
<section id="appendix-how-does-rfit-rank-regression-work" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="appendix-how-does-rfit-rank-regression-work"><span class="header-section-number">6.9</span> Appendix: How does Rfit rank regression work?</h2>
<p><strong>The core idea</strong></p>
<p>Most statistical analyses compare groups by calculating averages and asking how far apart those averages are. This works well when the data are well-behaved, but averages are can be greatly affected by a small number of unusually high or low outlier values.</p>
<p>Rfit takes a different approach. Instead of working with the raw measurements, it first converts every observation into its rank, that is, its position in the ordered list of all values. The lowest observation gets rank 1, the next gets rank 2, and so on. The analysis is then carried out on these ranks rather than the original numbers.</p>
<p>Because a rank only records where a value sits relative to the others, not how extreme it actually is, an outlier that is, say, ten times larger than the next highest value has no more influence than if it were just slightly larger. The ranks are far less sensitive to those extreme observations.</p>
<p><strong>How Rfit differs from ordinary least squares regression</strong></p>
<p>Standard linear regression finds the line of best fit by minimizing the sum of squared distances between each data point and the line. Squaring those distances means large errors caused by outliers count disproportionately and can distort the fitted line substantially.</p>
<p>Rfit uses the same idea of fitting a line through the data, but it minimizes a rank-based criterion instead of squared distances. In practical terms this means: - Outliers are handled gracefully. A single extreme value cannot pull the fitted line away from where the bulk of the data sit. - Covariates are still adjusted for. Just like standard regression, Rfit can include additional variables — such as study site or patient age — to account for factors that are not the primary focus of interest. - The output is familiar. Rfit produces coefficient estimates, standard errors, and p-values in the same format as ordinary regression, making results straightforward to interpret. - Efficiency is preserved. When data are perfectly normally Rfit is about 95% as efficient, meaning very little statistical power is sacrificed for the added robustness.</p>
<p><strong>Why does this matter?</strong></p>
<p>In many real-world datasets, such as biology experiments, clinical measurements, and laboratory assays, a small proportion of observations fall far outside the typical range. These might reflect genuine biological variation, data-entry errors, or rare events. Whatever the cause, they can mislead standard methods. Rfit provides a middle ground: it is more resistant to those unusual values than ordinary regression, yet unlike a simple non-parametric test it can still adjust for other variables and handle complex study designs. When data contain outliers, simulations show Rfit detecting real treatment effects at higher rates than either standard regression or unadjusted rank tests.</p>
<p><strong>In summary</strong></p>
<p>Rfit is a robust regression method that replaces the raw data with ranks before fitting a standard regression model. It combines the interpretability and flexibility of regression — including the ability to adjust for other variables — with the outlier-resistance of rank-based methods. It is most valuable when data contain skewed distributions or extreme observations, and it sacrifices little when data are well-behaved.</p>
<p><strong>How to interpret the rfit coefficients</strong></p>
<p>The coefficients produced by Rfit are interpreted in the same way as those from ordinary linear regression. Each coefficient represents the estimated shift in the outcome associated with a one-unit increase in that predictor, after holding all other predictors constant.</p>
<p>For example, in a clinical trial model of the form “rfit(outcome ~ treatment + site)”, the coefficient for treatment estimates the typical difference in outcome between the treatment and control arms, adjusted for site. A positive value means the treatment group tended to score higher; a negative value means lower. The site coefficients capture how much each site’s typical outcome differs from the reference site, after accounting for treatment.</p>
<p>One subtlety is worth noting. Because Rfit works on ranks internally, the coefficient is technically an estimate of a shift parameter, that is, the amount by which the entire distribution of outcomes in one group is displaced relative to the other. It is not just a comparison of the means or a comparison of the medians.</p>
<p>The p-value and confidence interval accompanying each coefficient are interpreted in the usual way: the p-value tests whether the true shift is zero, and the confidence interval gives a plausible range for the size of the effect. Because Rfit is robust, these inferential summaries are more reliable than those from ordinary regression when the data contain outliers or are non-normally distributed.</p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-brunner2018" class="csl-entry" role="listitem">
Brunner, Edgar, Arne C. Bathke, and Frank Konietschke. 2018. <em>Rank and Pseudo-Rank Procedures for Independent Observations in Factorial Designs: Using r and SAS</em>. Springer Series in Statistics. Springer.
</div>
<div id="ref-jaeckel1972" class="csl-entry" role="listitem">
Jaeckel, Louis A. 1972. <span>“Estimating Regression Coefficients by Minimizing the Dispersion of the Residuals.”</span> <em>Annals of Mathematical Statistics</em> 43: 1449–58.
</div>
<div id="ref-kloke2012" class="csl-entry" role="listitem">
Kloke, John D., and Joseph W. McKean. 2012. <span>“Rfit: Rank-Based Estimation for Linear Models.”</span> <em>The R Journal</em> 4 (2): 57–64.
</div>
<div id="ref-kloke2015" class="csl-entry" role="listitem">
Kloke, John, and Joseph W. McKean. 2015. <em>Nonparametric Statistical Methods Using r</em>. Chapman; Hall/CRC.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch05-rank-one-predictor.html" class="pagination-link" aria-label="If you have non-normal data and one explanatory variable: Wilcoxon and Kruskal-Wallis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">If you have non-normal data and one explanatory variable: Wilcoxon and Kruskal-Wallis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch07-survival-analysis.html" class="pagination-link" aria-label="Survival Analysis">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>Data that are not normally distributed can cause loss of power and poor p-values for t-test, analysis of variance and multiple regression. The Wilcoxon rank sum test and Kruskal-Wallis help if you only have one explanatory variable, but what if you have more than one variable that affects the outcome? In this chapter we'll look at rank methods that allow for multiple explanatory variables.</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>Load these libraries to run the examples in this chapter.</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(coin)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rfit)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rankFD)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="fu">## Overview of rank methods for multiple explanatory variables</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>Rank analysis is an active area of statistics research. Several R packages and tools are available. We'll focus on these two: </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Van Elteren stratified Wilcoxon test (coin package)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rank-based regression (Rfit package)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="fu">### Van Elteren stratified Wilcoxon test with coin</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>The van Elteren stratified Wilcoxon test was first published in 1960. Among its advantages are the facts that it is fairly widely known and has been used for FDA submissions and in articles published in the major medical and scientific journals. It has some disadvantages that we'll note shortly. It is available in standard statistics packages such as SAS and R. We'll use the van Elteren test from the R package coin.</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a><span class="fu">### Rank-based regression with Rfit</span></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>Rfit is built around rank-based regression as an alternative to ordinary least squares regression. The Rfit package accompanies the textbook “Nonparametric Statistical Methods Using R” by John Kloke and Joseph W. McKean <span class="co">[</span><span class="ot">@kloke2015</span><span class="co">]</span>. Think of it as a rank-based alternative to lm(). The appendix to this chapter gives a brief comparison of rfit versus traditional least-squares regression.</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a><span class="fu">### rankFD for Rank-based analysis of variance and factorial design </span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>The rankFD package accompanies the textbook "Rank and Pseudo-Rank Procedures for Independent Observations in Factorial Designs" by Brunner <span class="co">[</span><span class="ot">@brunner2018</span><span class="co">]</span>.</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>rankFD is built around nonparametric hypothesis testing in factorial designs. It is particulalry useful if you are looking for a rank-based alternative for factorial analysis of variance and experiment design.</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example data set with outliers</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a>We'll use this anova.2way.data.outlier data set for some of the examples.</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier <span class="ot">=</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb17-53"><a href="#cb17-53" aria-hidden="true" tabindex="-1"></a><span class="sc">~</span>Treatment, <span class="sc">~</span>Litter, <span class="sc">~</span>Response,</span>
<span id="cb17-54"><a href="#cb17-54" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">4</span>,</span>
<span id="cb17-55"><a href="#cb17-55" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">8</span>,</span>
<span id="cb17-56"><a href="#cb17-56" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">11</span>,</span>
<span id="cb17-57"><a href="#cb17-57" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">12</span>,</span>
<span id="cb17-58"><a href="#cb17-58" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">13</span>,</span>
<span id="cb17-59"><a href="#cb17-59" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">15</span>,</span>
<span id="cb17-60"><a href="#cb17-60" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">20</span>,</span>
<span id="cb17-61"><a href="#cb17-61" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">32</span>,</span>
<span id="cb17-62"><a href="#cb17-62" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">10</span>,</span>
<span id="cb17-63"><a href="#cb17-63" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">15</span>,</span>
<span id="cb17-64"><a href="#cb17-64" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">16</span>,</span>
<span id="cb17-65"><a href="#cb17-65" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">17</span>,</span>
<span id="cb17-66"><a href="#cb17-66" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">19</span>,</span>
<span id="cb17-67"><a href="#cb17-67" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">20</span>,</span>
<span id="cb17-68"><a href="#cb17-68" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb17-69"><a href="#cb17-69" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">31</span></span>
<span id="cb17-70"><a href="#cb17-70" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-71"><a href="#cb17-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-72"><a href="#cb17-72" aria-hidden="true" tabindex="-1"></a><span class="co"># van Elteren stratified Wilcoxon test from the coin R package  </span></span>
<span id="cb17-73"><a href="#cb17-73" aria-hidden="true" tabindex="-1"></a><span class="co"># requires that covariates are defined to be factors</span></span>
<span id="cb17-74"><a href="#cb17-74" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Litter <span class="ot">=</span> <span class="fu">as.factor</span>(anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Litter)</span>
<span id="cb17-75"><a href="#cb17-75" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Treatment <span class="ot">=</span> <span class="fu">as.factor</span>(anova<span class="fl">.2</span>way.data.outlier<span class="sc">$</span>Treatment)</span>
<span id="cb17-76"><a href="#cb17-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-77"><a href="#cb17-77" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(anova<span class="fl">.2</span>way.data.outlier)</span>
<span id="cb17-78"><a href="#cb17-78" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-79"><a href="#cb17-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-80"><a href="#cb17-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-83"><a href="#cb17-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-84"><a href="#cb17-84" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(anova<span class="fl">.2</span>way.data.outlier, <span class="fu">aes</span>(<span class="at">y=</span>Response, <span class="at">x=</span>Treatment)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-85"><a href="#cb17-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>Litter) <span class="sc">+</span></span>
<span id="cb17-86"><a href="#cb17-86" aria-hidden="true" tabindex="-1"></a><span class="fu">ggtitle</span>(<span class="st">"Response to treatment  </span><span class="sc">\n</span><span class="st">broken out by Litter, with outliers"</span>)</span>
<span id="cb17-87"><a href="#cb17-87" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-88"><a href="#cb17-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-89"><a href="#cb17-89" aria-hidden="true" tabindex="-1"></a>The outliers in litter 4 are evident, as is the large difference in response between the litters.</span>
<span id="cb17-90"><a href="#cb17-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-91"><a href="#cb17-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-92"><a href="#cb17-92" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis using standard anova</span></span>
<span id="cb17-93"><a href="#cb17-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-94"><a href="#cb17-94" aria-hidden="true" tabindex="-1"></a>Start with an ordinary two-way ANOVA for this data.</span>
<span id="cb17-95"><a href="#cb17-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-98"><a href="#cb17-98" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-99"><a href="#cb17-99" aria-hidden="true" tabindex="-1"></a>lm<span class="fl">.2</span>way.outlier <span class="ot">=</span> <span class="fu">lm</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment,</span>
<span id="cb17-100"><a href="#cb17-100" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span> anova<span class="fl">.2</span>way.data.outlier)</span>
<span id="cb17-101"><a href="#cb17-101" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(lm<span class="fl">.2</span>way.outlier)</span>
<span id="cb17-102"><a href="#cb17-102" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-103"><a href="#cb17-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-104"><a href="#cb17-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-105"><a href="#cb17-105" aria-hidden="true" tabindex="-1"></a>The ordinary two-way ANOVA confirms the additional variability due to litter (p = 0.00066) but treatment is not significant (p = 0.054). </span>
<span id="cb17-106"><a href="#cb17-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-107"><a href="#cb17-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-108"><a href="#cb17-108" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rank-based analysis using the van Elteren stratified Wilcoxon test</span></span>
<span id="cb17-109"><a href="#cb17-109" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb17-110"><a href="#cb17-110" aria-hidden="true" tabindex="-1"></a>The syntax for the van Elteren stratified Wilcoxon test is to specify the  usual formula "Response ~ Treatment" followed by a vertical bar "|" and the stratification variable, in this case "Litter". As the code below shows, this gives "Response ~ Treatment | Litter". Note also that the van Elteren stratified Wilcoxon test from the R package coin requires that the explanatory variables are defined to be factors.</span>
<span id="cb17-111"><a href="#cb17-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-114"><a href="#cb17-114" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-115"><a href="#cb17-115" aria-hidden="true" tabindex="-1"></a><span class="co"># van Elteren stratified Wilcoxon test</span></span>
<span id="cb17-116"><a href="#cb17-116" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox_test</span>(Response <span class="sc">~</span> Treatment <span class="sc">|</span> Litter,</span>
<span id="cb17-117"><a href="#cb17-117" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data         =</span> anova<span class="fl">.2</span>way.data.outlier,</span>
<span id="cb17-118"><a href="#cb17-118" aria-hidden="true" tabindex="-1"></a>                  <span class="at">distribution =</span> <span class="st">"asymptotic"</span>)</span>
<span id="cb17-119"><a href="#cb17-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-120"><a href="#cb17-120" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-121"><a href="#cb17-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-122"><a href="#cb17-122" aria-hidden="true" tabindex="-1"></a>The van Elteren stratified Wilcoxon test gives p = 0.008 for treatment, stratifying for Litter, which is an improvement over the non-significant result for the two-way anova.</span>
<span id="cb17-123"><a href="#cb17-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-124"><a href="#cb17-124" aria-hidden="true" tabindex="-1"></a>Watch out for errors in the formula syntax for the stratified Wilcoxon test using wilcox_test. An easy mistake to make (I know, because I've done it) is formatting a stratified test as Response ~ Treatment + Litter. The stratified Wilcoxon using wilcox_test from the coin package must be formatted with a vertical bar indicating the blocking variable: Response ~ Treatment | Litter. </span>
<span id="cb17-125"><a href="#cb17-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-126"><a href="#cb17-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Rank-based analysis using the Rfit package</span></span>
<span id="cb17-127"><a href="#cb17-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-128"><a href="#cb17-128" aria-hidden="true" tabindex="-1"></a>Another alternative for rank-based analysis is the Rfit package. To run these examples, install and load the package with this code:</span>
<span id="cb17-129"><a href="#cb17-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-130"><a href="#cb17-130" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-133"><a href="#cb17-133" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-134"><a href="#cb17-134" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("Rfit") # if not already installed</span></span>
<span id="cb17-135"><a href="#cb17-135" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Rfit)</span>
<span id="cb17-136"><a href="#cb17-136" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-137"><a href="#cb17-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-138"><a href="#cb17-138" aria-hidden="true" tabindex="-1"></a>Here is the analysis of the outlier data, with litter and treatment as the two explanatory variables. The function rfit() performs the analysis.</span>
<span id="cb17-139"><a href="#cb17-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-140"><a href="#cb17-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-143"><a href="#cb17-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-144"><a href="#cb17-144" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data.outlier.rfit <span class="ot">=</span> <span class="fu">with</span>(anova<span class="fl">.2</span>way.data.outlier,</span>
<span id="cb17-145"><a href="#cb17-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rfit</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment))</span>
<span id="cb17-146"><a href="#cb17-146" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova<span class="fl">.2</span>way.data.outlier.rfit)</span>
<span id="cb17-147"><a href="#cb17-147" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-148"><a href="#cb17-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-149"><a href="#cb17-149" aria-hidden="true" tabindex="-1"></a>The rank-based rfit test indicates that treatment has a significant effect (p = 0.017). Compare this result to the conventional two-way ANOVA result of p = 0.054, which indicated that treatment was not significant.</span>
<span id="cb17-150"><a href="#cb17-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-151"><a href="#cb17-151" aria-hidden="true" tabindex="-1"></a>The output also indicates that there are significant differences among the litters. </span>
<span id="cb17-152"><a href="#cb17-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-153"><a href="#cb17-153" aria-hidden="true" tabindex="-1"></a>We could have started the analysis with an interaction test, using the Rfit function raov. The formula “Response ~ Litter * Treatment” specifies the interaction test.</span>
<span id="cb17-154"><a href="#cb17-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-157"><a href="#cb17-157" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-158"><a href="#cb17-158" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(anova<span class="fl">.2</span>way.data.outlier, <span class="fu">raov</span>(Response <span class="sc">~</span> Litter <span class="sc">*</span> Treatment))</span>
<span id="cb17-159"><a href="#cb17-159" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-160"><a href="#cb17-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-161"><a href="#cb17-161" aria-hidden="true" tabindex="-1"></a>The interaction test is not significant (p = 0.937), indicating that there is no interaction between treatment and litter. So, the model without interaction was suitable. </span>
<span id="cb17-162"><a href="#cb17-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-163"><a href="#cb17-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-164"><a href="#cb17-164" aria-hidden="true" tabindex="-1"></a>We can also examine the results for rfit for the data with no outliers.</span>
<span id="cb17-165"><a href="#cb17-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-166"><a href="#cb17-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-169"><a href="#cb17-169" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-170"><a href="#cb17-170" aria-hidden="true" tabindex="-1"></a>anova<span class="fl">.2</span>way.data <span class="ot">=</span> tibble<span class="sc">::</span><span class="fu">tribble</span>(</span>
<span id="cb17-171"><a href="#cb17-171" aria-hidden="true" tabindex="-1"></a><span class="sc">~</span>Treatment, <span class="sc">~</span>Litter, <span class="sc">~</span>Response,</span>
<span id="cb17-172"><a href="#cb17-172" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">4</span>,</span>
<span id="cb17-173"><a href="#cb17-173" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.1"</span>, <span class="dv">8</span>,</span>
<span id="cb17-174"><a href="#cb17-174" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">11</span>,</span>
<span id="cb17-175"><a href="#cb17-175" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.2"</span>, <span class="dv">12</span>,</span>
<span id="cb17-176"><a href="#cb17-176" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">13</span>,</span>
<span id="cb17-177"><a href="#cb17-177" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.3"</span>, <span class="dv">15</span>,</span>
<span id="cb17-178"><a href="#cb17-178" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">20</span>,</span>
<span id="cb17-179"><a href="#cb17-179" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Drug"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb17-180"><a href="#cb17-180" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">10</span>,</span>
<span id="cb17-181"><a href="#cb17-181" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.1"</span>, <span class="dv">15</span>,</span>
<span id="cb17-182"><a href="#cb17-182" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">16</span>,</span>
<span id="cb17-183"><a href="#cb17-183" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.2"</span>, <span class="dv">17</span>,</span>
<span id="cb17-184"><a href="#cb17-184" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">19</span>,</span>
<span id="cb17-185"><a href="#cb17-185" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.3"</span>, <span class="dv">20</span>,</span>
<span id="cb17-186"><a href="#cb17-186" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">21</span>,</span>
<span id="cb17-187"><a href="#cb17-187" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Placebo"</span>, <span class="st">"Litter.4"</span>, <span class="dv">23</span></span>
<span id="cb17-188"><a href="#cb17-188" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-189"><a href="#cb17-189" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-190"><a href="#cb17-190" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-191"><a href="#cb17-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-194"><a href="#cb17-194" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb17-195"><a href="#cb17-195" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">rfit</span>(Response <span class="sc">~</span> Litter <span class="sc">+</span> Treatment, <span class="at">data =</span> anova<span class="fl">.2</span>way.data))</span>
<span id="cb17-196"><a href="#cb17-196" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-197"><a href="#cb17-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-198"><a href="#cb17-198" aria-hidden="true" tabindex="-1"></a>We see that, for the data with no outliers, the p-value for the rfit method (p = 0.003456) is similar to the p-value for the classical analysis of variance (p = 0.000545), although not quite so good.</span>
<span id="cb17-199"><a href="#cb17-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-200"><a href="#cb17-200" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-201"><a href="#cb17-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-202"><a href="#cb17-202" aria-hidden="true" tabindex="-1"></a><span class="fu">## Compare power for Wilcoxon, stratified Wilcoxon and rfit: data with outliers</span></span>
<span id="cb17-203"><a href="#cb17-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-204"><a href="#cb17-204" aria-hidden="true" tabindex="-1"></a>Let's run some simulations to compare power for these rank methods. We'll start with a data set that has outliers. Code for the simulations is on the book website.</span>
<span id="cb17-205"><a href="#cb17-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-206"><a href="#cb17-206" aria-hidden="true" tabindex="-1"></a>For this first simulation, we'll assume the following.</span>
<span id="cb17-207"><a href="#cb17-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-208"><a href="#cb17-208" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Two group: "Control" and "Treatment"</span>
<span id="cb17-209"><a href="#cb17-209" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Response (y) variable is "Outcome"</span>
<span id="cb17-210"><a href="#cb17-210" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Study is performed at 9 sites. Sites are a source of variation.</span>
<span id="cb17-211"><a href="#cb17-211" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The number of observations per site in each group is 4, 6 or 8. </span>
<span id="cb17-212"><a href="#cb17-212" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Within each site, within each treatment group, data is randomly sampled from a normal distribution (mean = 20, sd = 4), with the addition of 2 outliers each to the "Control" and "Treatment" groups within each site.</span>
<span id="cb17-213"><a href="#cb17-213" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Within site the Treatment group is shifted relative to the Control group. We use a range of shift values from 1 to 5 by 0.5</span>
<span id="cb17-214"><a href="#cb17-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-215"><a href="#cb17-215" aria-hidden="true" tabindex="-1"></a>The graph below shows the data for one simulation. Notice both the differences among the sites and the differences between treatment groups within each site.</span>
<span id="cb17-216"><a href="#cb17-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-217"><a href="#cb17-217" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, out.width="100%"}</span></span>
<span id="cb17-218"><a href="#cb17-218" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-219"><a href="#cb17-219" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/rank_power_sim_w_outliers.png"</span>)</span>
<span id="cb17-220"><a href="#cb17-220" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-221"><a href="#cb17-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-222"><a href="#cb17-222" aria-hidden="true" tabindex="-1"></a>The graph below shows the power curves comparing the analysis methods over many simulations.</span>
<span id="cb17-223"><a href="#cb17-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-224"><a href="#cb17-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, out.width="100%"}</span></span>
<span id="cb17-225"><a href="#cb17-225" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-226"><a href="#cb17-226" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/rank_sim_power_curves_w_outliers.png"</span>)</span>
<span id="cb17-227"><a href="#cb17-227" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-228"><a href="#cb17-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-229"><a href="#cb17-229" aria-hidden="true" tabindex="-1"></a>For this simulated data set with an important covariate (site) and outliers, the methods that ignore the covariate (t-test and Wilcoxon rank sum) have the lowest power. The linear model that adjusts for the site covariate has more power, but lower power than the stratified Wilcoxon and rfit, both of which adjust for the site covariate and handle the outliers without inflating the variance.</span>
<span id="cb17-230"><a href="#cb17-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-231"><a href="#cb17-231" aria-hidden="true" tabindex="-1"></a>How does the power compare for data without outliers? We'll look at that next.</span>
<span id="cb17-232"><a href="#cb17-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-233"><a href="#cb17-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-234"><a href="#cb17-234" aria-hidden="true" tabindex="-1"></a><span class="fu">## Compare power for Wilcoxon, stratified Wilcoxon and rfit: no outliers</span></span>
<span id="cb17-235"><a href="#cb17-235" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-236"><a href="#cb17-236" aria-hidden="true" tabindex="-1"></a>Now we'll compare the power for the 5 methods for data with no outliers. The data is the same as for the simulation above, except that no outliers are added.</span>
<span id="cb17-237"><a href="#cb17-237" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-238"><a href="#cb17-238" aria-hidden="true" tabindex="-1"></a>The graph below shows the data for one simulation. Notice both the differences among the sites and the differences between treatment groups within each site.</span>
<span id="cb17-239"><a href="#cb17-239" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-240"><a href="#cb17-240" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, out.width="100%"}</span></span>
<span id="cb17-241"><a href="#cb17-241" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-242"><a href="#cb17-242" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/rank_power_sim_no_outliers.png"</span>)</span>
<span id="cb17-243"><a href="#cb17-243" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-244"><a href="#cb17-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-245"><a href="#cb17-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-246"><a href="#cb17-246" aria-hidden="true" tabindex="-1"></a>The graph below shows the power curves comparing the analysis methods over many simulations.</span>
<span id="cb17-247"><a href="#cb17-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-248"><a href="#cb17-248" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, out.width="100%"}</span></span>
<span id="cb17-249"><a href="#cb17-249" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb17-250"><a href="#cb17-250" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"figures/rank_sim_power_curves_no_outliers.png"</span>)</span>
<span id="cb17-251"><a href="#cb17-251" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb17-252"><a href="#cb17-252" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-253"><a href="#cb17-253" aria-hidden="true" tabindex="-1"></a>For this simulated data set with an important covariate (site) but no outliers, the two methods that ignore the site covariate (linear model with no site adjustment and Wilcoxon rank sum) have the lowest power. The stratified Wilcoxon, rfit, and linear model that adjust for the site covariate all have similar power. For data that are normally distributed with no outliers, rfit is expected to have 95% of the power of the linear model. So the results seen here are not surprising.</span>
<span id="cb17-254"><a href="#cb17-254" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-255"><a href="#cb17-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-256"><a href="#cb17-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## Limitations of the rank methods</span></span>
<span id="cb17-257"><a href="#cb17-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-258"><a href="#cb17-258" aria-hidden="true" tabindex="-1"></a>Every method (including t-tests, anova, and linear regression) has assumptions and limitations. Here we note limitations of the rank methods considered in this chapter.</span>
<span id="cb17-259"><a href="#cb17-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-260"><a href="#cb17-260" aria-hidden="true" tabindex="-1"></a><span class="fu">### Limitations of the van Elteren stratified Wilcoxon test</span></span>
<span id="cb17-261"><a href="#cb17-261" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb17-262"><a href="#cb17-262" aria-hidden="true" tabindex="-1"></a>The van Elteren test (1960) is a stratified extension of the Wilcoxon–Mann–Whitney rank-sum test. It combines within-stratum rank statistics into a single weighted statistic, controlling one or more stratification factors. While useful, the procedure carries several important limitations. These are described in some detail in the textbook by Brunner <span class="co">[</span><span class="ot">@brunner2018</span><span class="co">]</span>.</span>
<span id="cb17-263"><a href="#cb17-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-264"><a href="#cb17-264" aria-hidden="true" tabindex="-1"></a>**Assumes uniform effect cross strata**</span>
<span id="cb17-265"><a href="#cb17-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-266"><a href="#cb17-266" aria-hidden="true" tabindex="-1"></a>The test combines stratum-level rank statistics by weighting them, implicitly assuming a common treatment effect across all strata. If the true effect varies considerably from stratum to stratum (there is a treatment-by-stratum interaction), the single combined p-value can be misleading. It is a good idea to look at the within-stratum results before relying solely on the overall test.</span>
<span id="cb17-267"><a href="#cb17-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-268"><a href="#cb17-268" aria-hidden="true" tabindex="-1"></a>**Reduced power with many small strata**</span>
<span id="cb17-269"><a href="#cb17-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-270"><a href="#cb17-270" aria-hidden="true" tabindex="-1"></a>When the number of strata is large relative to the total sample size, so that many strata contain only a handful of observations, the within-stratum rank information becomes very sparse. The test can lose power compared to an unstratified Wilcoxon test, or even compared to a parametric approach such as a mixed model. A common guideline is to avoid strata with fewer than five observations per treatment arm.</span>
<span id="cb17-271"><a href="#cb17-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-272"><a href="#cb17-272" aria-hidden="true" tabindex="-1"></a>**Ties require careful handling**</span>
<span id="cb17-273"><a href="#cb17-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-274"><a href="#cb17-274" aria-hidden="true" tabindex="-1"></a>Like all rank-based methods, the van Elteren test requires an adjustment when tied observations are present. Standard mid-rank tie-breaking is incorporated into the usual variance formula, but with heavy ties (for example, an ordinal outcome with only a few levels) the normal approximation to the null distribution can be poor, inflating the Type I error rate. In such cases a permutation or exact version of the test should be considered.</span>
<span id="cb17-275"><a href="#cb17-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-276"><a href="#cb17-276" aria-hidden="true" tabindex="-1"></a>**No built-in effect size estimate**</span>
<span id="cb17-277"><a href="#cb17-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-278"><a href="#cb17-278" aria-hidden="true" tabindex="-1"></a>The test produces a p-value, but it does not directly provide an effect-size estimate or confidence interval. To quantify the magnitude of the treatment difference, a companion measure such as the stratified Hodges–Lehmann location shift must be computed separately. Reporting a p-value alone may be insufficient for clinical or scientific interpretation.</span>
<span id="cb17-279"><a href="#cb17-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-280"><a href="#cb17-280" aria-hidden="true" tabindex="-1"></a>**Asymptotic validity requires adequate sample size**</span>
<span id="cb17-281"><a href="#cb17-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-282"><a href="#cb17-282" aria-hidden="true" tabindex="-1"></a>The standard test relies on a large-sample normal approximation. With very small per-stratum sample sizes the approximation may be unreliable. Exact conditional permutation tests are available but are computationally intensive, and software implementations vary in whether they offer this option.</span>
<span id="cb17-283"><a href="#cb17-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-284"><a href="#cb17-284" aria-hidden="true" tabindex="-1"></a>**Sensitive to stratum definition**</span>
<span id="cb17-285"><a href="#cb17-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-286"><a href="#cb17-286" aria-hidden="true" tabindex="-1"></a>The stratification scheme should be defined before the analysis and should reflect genuine a priori prognostic factors. Post-hoc choice of strata or collapsing / splitting strata after seeing the data inflates the Type I error. Regulatory guidance (such as ICH E9) requires pre-specification of the stratification factors in the statistical analysis plan.</span>
<span id="cb17-287"><a href="#cb17-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-288"><a href="#cb17-288" aria-hidden="true" tabindex="-1"></a>**Practical guidance**</span>
<span id="cb17-289"><a href="#cb17-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-290"><a href="#cb17-290" aria-hidden="true" tabindex="-1"></a>None of these limitations invalidates the van Elteren test. It remains a widely-used, nonparametric option for stratified two-group comparisons in clinical trials and observational studies. The key safeguards are to pre-specify the stratification factors and weighting scheme, verify the homogeneity-of-effect assumption, ensure strata are not too small, and supplement the p-value with a suitable effect-size estimate and confidence interval.</span>
<span id="cb17-291"><a href="#cb17-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-292"><a href="#cb17-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-293"><a href="#cb17-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-294"><a href="#cb17-294" aria-hidden="true" tabindex="-1"></a><span class="fu">### Limitations of Rfit</span></span>
<span id="cb17-295"><a href="#cb17-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-296"><a href="#cb17-296" aria-hidden="true" tabindex="-1"></a>The rfit package <span class="co">[</span><span class="ot">@kloke2012</span><span class="co">]</span> implements rank-based estimation and inference for linear models in R. It fits regression coefficients by minimizing a rank-based dispersion function derived from Jaeckel <span class="co">[</span><span class="ot">@jaeckel1972</span><span class="co">]</span>, producing estimates that are robust to non-normality and heavy-tailed errors while retaining high efficiency relative to ordinary least squares. Despite these advantages, the approach has a number of limitations that practitioners should understand before adopting it as a primary analytical strategy.</span>
<span id="cb17-297"><a href="#cb17-297" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-298"><a href="#cb17-298" aria-hidden="true" tabindex="-1"></a>**Relies on asymptotic theory. May be inaccurate with small samples.**</span>
<span id="cb17-299"><a href="#cb17-299" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-300"><a href="#cb17-300" aria-hidden="true" tabindex="-1"></a>The standard errors, t-statistics, and F-statistics produced by rfit are justified by large-sample asymptotic arguments. In small datasets the normal and chi-squared approximations underpinning these quantities can be unreliable, leading to poorly calibrated p-values and confidence intervals.</span>
<span id="cb17-301"><a href="#cb17-301" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-302"><a href="#cb17-302" aria-hidden="true" tabindex="-1"></a>**Choice of score function can affect results**</span>
<span id="cb17-303"><a href="#cb17-303" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-304"><a href="#cb17-304" aria-hidden="true" tabindex="-1"></a>The method requires selection of a score function (e.g., Wilcoxon, sign, normal, Bent scores) that determines what distributional shape is being targeted. The default Wilcoxon scores are optimal when the error distribution is logistic. Choosing an inappropriate score function can reduce efficiency relative to least squares or relative to the correctly specified rank estimator.</span>
<span id="cb17-305"><a href="#cb17-305" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-306"><a href="#cb17-306" aria-hidden="true" tabindex="-1"></a>**Estimates are location shift, not conditional means**</span>
<span id="cb17-307"><a href="#cb17-307" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-308"><a href="#cb17-308" aria-hidden="true" tabindex="-1"></a>Rank-based regression via rfit estimates shift parameters in a location model rather than conditional means. Location shift as an effect descriptor is less familiar to many users than effect sizes based on means.</span>
<span id="cb17-309"><a href="#cb17-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-310"><a href="#cb17-310" aria-hidden="true" tabindex="-1"></a>**Ties in the outcome degrade performance**</span>
<span id="cb17-311"><a href="#cb17-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-312"><a href="#cb17-312" aria-hidden="true" tabindex="-1"></a>Like all rank-based methods, rfit uses mid-rank tie-breaking by default. When the outcome contains many ties, as is common with ordinal scales, rounded measurements, or clumped continuous data, the dispersion function becomes less sensitive to differences among tied values and efficiency is reduced</span>
<span id="cb17-313"><a href="#cb17-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-314"><a href="#cb17-314" aria-hidden="true" tabindex="-1"></a>**Limited availability and regulatory acceptance**</span>
<span id="cb17-315"><a href="#cb17-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-316"><a href="#cb17-316" aria-hidden="true" tabindex="-1"></a>The Rfit package (Kloke &amp; McKean, 2012) is available in R but has no direct equivalent in SAS, Stata, or Python. Moreover, rank-based linear regression has little presence in FDA or EMA guidance documents, so its use as a primary analysis in confirmatory clinical trials requires additional scientific justification compared with OLS or prespecified nonparametric alternatives.</span>
<span id="cb17-317"><a href="#cb17-317" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-318"><a href="#cb17-318" aria-hidden="true" tabindex="-1"></a>**Practical guidance**</span>
<span id="cb17-319"><a href="#cb17-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-320"><a href="#cb17-320" aria-hidden="true" tabindex="-1"></a>Rfit is best suited to continuous, approximately symmetric outcomes in moderately large samples where robustness to heavy tails or outliers in the response is the primary concern. For small samples, sparse or ordinal outcomes, or settings requiring regulatory acceptance, alternative approaches should be considered alongside or instead of rfit.</span>
<span id="cb17-321"><a href="#cb17-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-322"><a href="#cb17-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-323"><a href="#cb17-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-324"><a href="#cb17-324" aria-hidden="true" tabindex="-1"></a><span class="fu">## Appendix: How does Rfit rank regression work?</span></span>
<span id="cb17-325"><a href="#cb17-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-326"><a href="#cb17-326" aria-hidden="true" tabindex="-1"></a>**The core idea**</span>
<span id="cb17-327"><a href="#cb17-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-328"><a href="#cb17-328" aria-hidden="true" tabindex="-1"></a>Most statistical analyses compare groups by calculating averages and asking how far apart those averages are. This works well when the data are well-behaved, but averages are can be greatly affected by a small number of unusually high or low outlier values.</span>
<span id="cb17-329"><a href="#cb17-329" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-330"><a href="#cb17-330" aria-hidden="true" tabindex="-1"></a>Rfit takes a different approach. Instead of working with the raw measurements, it first converts every observation into its rank, that is, its position in the ordered list of all values. The lowest observation gets rank 1, the next gets rank 2, and so on. The analysis is then carried out on these ranks rather than the original numbers.</span>
<span id="cb17-331"><a href="#cb17-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-332"><a href="#cb17-332" aria-hidden="true" tabindex="-1"></a>Because a rank only records where a value sits relative to the others, not how extreme it actually is, an outlier that is, say, ten times larger than the next highest value has no more influence than if it were just slightly larger. The ranks are far less sensitive to those extreme observations.</span>
<span id="cb17-333"><a href="#cb17-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-334"><a href="#cb17-334" aria-hidden="true" tabindex="-1"></a>**How Rfit differs from ordinary least squares regression**</span>
<span id="cb17-335"><a href="#cb17-335" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-336"><a href="#cb17-336" aria-hidden="true" tabindex="-1"></a>Standard linear regression finds the line of best fit by minimizing the sum of squared distances between each data point and the line. Squaring those distances means large errors caused by outliers count disproportionately and can distort the fitted line substantially.</span>
<span id="cb17-337"><a href="#cb17-337" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-338"><a href="#cb17-338" aria-hidden="true" tabindex="-1"></a>Rfit uses the same idea of fitting a line through the data, but it minimizes a rank-based criterion instead of squared distances. In practical terms this means:</span>
<span id="cb17-339"><a href="#cb17-339" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Outliers are handled gracefully. A single extreme value cannot pull the fitted line away from where the bulk of the data sit.</span>
<span id="cb17-340"><a href="#cb17-340" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Covariates are still adjusted for. Just like standard regression, Rfit can include additional variables — such as study site or patient age — to account for factors that are not the primary focus of interest.</span>
<span id="cb17-341"><a href="#cb17-341" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>The output is familiar. Rfit produces coefficient estimates, standard errors, and p-values in the same format as ordinary regression, making results straightforward to interpret.</span>
<span id="cb17-342"><a href="#cb17-342" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Efficiency is preserved. When data are perfectly normally Rfit is about 95% as efficient, meaning very little statistical power is sacrificed for the added robustness.</span>
<span id="cb17-343"><a href="#cb17-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-344"><a href="#cb17-344" aria-hidden="true" tabindex="-1"></a>**Why does this matter?**</span>
<span id="cb17-345"><a href="#cb17-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-346"><a href="#cb17-346" aria-hidden="true" tabindex="-1"></a>In many real-world datasets, such as biology experiments, clinical measurements, and laboratory assays, a small proportion of observations fall far outside the typical range. These might reflect genuine biological variation, data-entry errors, or rare events. Whatever the cause, they can mislead standard methods.</span>
<span id="cb17-347"><a href="#cb17-347" aria-hidden="true" tabindex="-1"></a>Rfit provides a middle ground: it is more resistant to those unusual values than ordinary regression, yet unlike a simple non-parametric test it can still adjust for other variables and handle complex study designs. When data contain outliers, simulations show Rfit detecting real treatment effects at higher rates than either standard regression or unadjusted rank tests.</span>
<span id="cb17-348"><a href="#cb17-348" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-349"><a href="#cb17-349" aria-hidden="true" tabindex="-1"></a>**In summary**</span>
<span id="cb17-350"><a href="#cb17-350" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-351"><a href="#cb17-351" aria-hidden="true" tabindex="-1"></a>Rfit is a robust regression method that replaces the raw data with ranks before fitting a standard regression model. It combines the interpretability and flexibility of regression — including the ability to adjust for other variables — with the outlier-resistance of rank-based methods. It is most valuable when data contain skewed distributions or extreme observations, and it sacrifices little when data are well-behaved.</span>
<span id="cb17-352"><a href="#cb17-352" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-353"><a href="#cb17-353" aria-hidden="true" tabindex="-1"></a>**How to interpret the rfit coefficients**</span>
<span id="cb17-354"><a href="#cb17-354" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-355"><a href="#cb17-355" aria-hidden="true" tabindex="-1"></a>The coefficients produced by Rfit are interpreted in the same way as those from ordinary linear regression. Each coefficient represents the estimated shift in the outcome associated with a one-unit increase in that predictor, after holding all other predictors constant.</span>
<span id="cb17-356"><a href="#cb17-356" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-357"><a href="#cb17-357" aria-hidden="true" tabindex="-1"></a>For example, in a clinical trial model of the form “rfit(outcome ~ treatment + site)”, the coefficient for treatment estimates the typical difference in outcome between the treatment and control arms, adjusted for site. A positive value means the treatment group tended to score higher; a negative value means lower. The site coefficients capture how much each site’s typical outcome differs from the reference site, after accounting for treatment.</span>
<span id="cb17-358"><a href="#cb17-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-359"><a href="#cb17-359" aria-hidden="true" tabindex="-1"></a>One subtlety is worth noting. Because Rfit works on ranks internally, the coefficient is technically an estimate of a shift parameter, that is, the amount by which the entire distribution of outcomes in one group is displaced relative to the other. It is not just a comparison of the means or a comparison of the medians.</span>
<span id="cb17-360"><a href="#cb17-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-361"><a href="#cb17-361" aria-hidden="true" tabindex="-1"></a>The p-value and confidence interval accompanying each coefficient are interpreted in the usual way: the p-value tests whether the true shift is zero, and the confidence interval gives a plausible range for the size of the effect. Because Rfit is robust, these inferential summaries are more reliable than those from ordinary regression when the data contain outliers or are non-normally distributed.</span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Stats001/pvalues/edit/main/chapters/ch06-rank-more-than-one-predictor.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Stats001/pvalues/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>