<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Practical examples of how to increase power, reduce sample size, and choose better statistics tests">

<title>15&nbsp; Avoid one-variable-at-a-time experiments. Use factorial experiment design. – How to Get P-Values Less Than 0.05 in Biological Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/ch16-rescue-factorial.html" rel="next">
<link href="../chapters/ch14-two-primary-analyses.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-24cd44e0416da4fd58bb0517b27b0746.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-21613c26995e5ad49e067cca7f3a46fb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-24cd44e0416da4fd58bb0517b27b0746.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../site_libs/kePrint-0.0.1/kePrint.js"></script>

<link href="../site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">



<link rel="stylesheet" href="../custom.css">
</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/ch15-avoid-OVAT.html"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Avoid one-variable-at-a-time experiments. Use factorial experiment design.</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">How to Get P-Values Less Than 0.05 in Biological Research</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/Stats001/pvalues" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch01-avoid-ttests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Avoid t-tests: Control for variables using multiple regression or ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch02-power-sample-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Calculate power and sample size if you want p &lt; 0.05</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch03-reduce-variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Increase sample size last: reduce unexplained variability first</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch04-robust-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">If you have normally distributed data with outliers: Robust tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch05-rank-one-predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">If you have non-normal data and one explanatory variable: Wilcoxon and Kruskal-Wallis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch06-rank-more-than-one-predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">If you have non-normal data and more than one explanatory variable: Rank methods for multiple explanatory variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch07-survival-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Survival Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch08-count-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">For count outcomes consider negative binomial regression and Wilcoxon tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch09-avoid-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Avoid turning quantitative variables into categorical variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch10-cmh-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Avoid Chi-Squared tests when you have ordered categories: use CMH tests instead</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch11-balancing-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Balancing variables across treatment groups is not sufficient to get best p-values</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch12-correlated-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Avoid correlated explanatory variables in multiple regression and ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch13-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Look (out) for interactions: when subgroups respond differently to treatment</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch14-two-primary-analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Use two primary analyses each with alpha 0.025 instead of one with 0.05</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch15-avoid-OVAT.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Avoid one-variable-at-a-time experiments. Use factorial experiment design.</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch16-rescue-factorial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Rescue failed experiments using fractional factorial designs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch17-multiple-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The wrong way and the right way to get p &lt; 0.05: multiple hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch18-right-goal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Is P &lt; 0.05 the right goal?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch19-p-greater-05.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">What if you still get p &gt; 0.05?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/ch20-claude-for-these-analyses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Don’t know R? Use Claude to run these analyses for you</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#an-intuitive-view-of-experiment-design-baking-cookies" id="toc-an-intuitive-view-of-experiment-design-baking-cookies" class="nav-link active" data-scroll-target="#an-intuitive-view-of-experiment-design-baking-cookies"><span class="header-section-number">15.1</span> An intuitive view of experiment design: baking cookies</a></li>
  <li><a href="#the-problems-with-one-variable-at-a-time" id="toc-the-problems-with-one-variable-at-a-time" class="nav-link" data-scroll-target="#the-problems-with-one-variable-at-a-time"><span class="header-section-number">15.2</span> The problems with “One variable at a time”</a></li>
  <li><a href="#are-interactions-important-in-medicine-and-in-biological-research" id="toc-are-interactions-important-in-medicine-and-in-biological-research" class="nav-link" data-scroll-target="#are-interactions-important-in-medicine-and-in-biological-research"><span class="header-section-number">15.3</span> Are interactions important in medicine and in biological research?</a></li>
  <li><a href="#factorial-experiment-design-an-alternative-to-ovat" id="toc-factorial-experiment-design-an-alternative-to-ovat" class="nav-link" data-scroll-target="#factorial-experiment-design-an-alternative-to-ovat"><span class="header-section-number">15.4</span> Factorial experiment design: an alternative to OVAT</a></li>
  <li><a href="#example-experiment-design-for-3-factors" id="toc-example-experiment-design-for-3-factors" class="nav-link" data-scroll-target="#example-experiment-design-for-3-factors"><span class="header-section-number">15.5</span> Example: experiment design for 3 factors</a></li>
  <li><a href="#factorial-designs-have-more-power-than-ovat-designs" id="toc-factorial-designs-have-more-power-than-ovat-designs" class="nav-link" data-scroll-target="#factorial-designs-have-more-power-than-ovat-designs"><span class="header-section-number">15.6</span> Factorial designs have more power than OVAT designs</a></li>
  <li><a href="#what-about-replication-in-ovat-versus-factorial-designs" id="toc-what-about-replication-in-ovat-versus-factorial-designs" class="nav-link" data-scroll-target="#what-about-replication-in-ovat-versus-factorial-designs"><span class="header-section-number">15.7</span> What about replication in OVAT versus factorial designs?</a></li>
  <li><a href="#statistical-analysis-of-factorial-designs" id="toc-statistical-analysis-of-factorial-designs" class="nav-link" data-scroll-target="#statistical-analysis-of-factorial-designs"><span class="header-section-number">15.8</span> Statistical analysis of factorial designs</a></li>
  <li><a href="#when-may-ovat-be-preferable" id="toc-when-may-ovat-be-preferable" class="nav-link" data-scroll-target="#when-may-ovat-be-preferable"><span class="header-section-number">15.9</span> When may OVAT be preferable?</a></li>
  <li><a href="#recommended-youtube-videos" id="toc-recommended-youtube-videos" class="nav-link" data-scroll-target="#recommended-youtube-videos"><span class="header-section-number">15.10</span> Recommended YouTube videos</a></li>
  <li><a href="#recommended-free-textbook-pdf" id="toc-recommended-free-textbook-pdf" class="nav-link" data-scroll-target="#recommended-free-textbook-pdf"><span class="header-section-number">15.11</span> Recommended free textbook PDF</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/Stats001/pvalues/edit/main/chapters/ch15-avoid-OVAT.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Stats001/pvalues/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Avoid one-variable-at-a-time experiments. Use factorial experiment design.</span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>You have likely heard the advice, “Hold everything constant, change one thing at a time”? This is the one-variable-at-a-time (OVAT) approach.</p>
<p>As you will see in this chapter, OVAT is often a very inefficient and ineffective way to perform an experiment. An alternative to OVAT is factorial experiment design, which you may have encountered as Design of Experiments (DOE).</p>
<p>Compared to OVAT, factorial design of experiments has several advantages:</p>
<ul>
<li>Quickly and efficiently test the effects of multiple factors.</li>
<li>Increase power.</li>
<li>Get better p-values.</li>
<li>Detect interactions missed by OVAT.</li>
</ul>
<p>Factorial designs provide more information with less work than OVAT experiments, as we’ll see. Let’s start with a familiar example: baking cookies.</p>
<section id="an-intuitive-view-of-experiment-design-baking-cookies" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="an-intuitive-view-of-experiment-design-baking-cookies"><span class="header-section-number">15.1</span> An intuitive view of experiment design: baking cookies</h2>
<p>Suppose we are baking cookies. We want to maximize the yield of good cookies. We think that the time in the oven and the temperature in the oven could affect the yield. We plan to bake 4 batches using different combinations of time and temperature in the oven.</p>
<p><strong>Plan 1.</strong> Here is one possible plan for the 4 batches.</p>
<p><img src="figures/OVAT-fig-01.PNG" class="img-fluid"></p>
<p>The x axis is time in the oven. 0 is a short time in the oven, and 1 is a long time.</p>
<p>The y axis is temperature in the oven. 0 is a low temperature in the oven, and 1 is a high temperature.</p>
<p>The table shows the time and temperature for each batch.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Batch number</th>
<th>Time</th>
<th>Temperature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Does Plan 1 seem like a good way to design the experiment? Why or why not? Clearly, it seems pretty inefficient and uninformative to test the short time and low temperature (0,0) combination twice, but not to test the short time and high temperature (1,0) combination at all.</p>
<p><strong>Plan 2.</strong> Here is an alternative plan for the 4 batches.</p>
<p><img src="figures/OVAT-fig-02.PNG" class="img-fluid"></p>
<p>The table shows the time and temperature for each batch.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Batch number</th>
<th>Time</th>
<th>Temperature</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>Does Plan 2 look like a better plan?</p>
</section>
<section id="the-problems-with-one-variable-at-a-time" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="the-problems-with-one-variable-at-a-time"><span class="header-section-number">15.2</span> The problems with “One variable at a time”</h2>
<p>So, what’s wrong with one variable at a time? Let’s look at an example of the OVAT method from the book “Improving Almost Anything” by George Box <span class="citation" data-cites="box2006">(<a href="references.html#ref-box2006" role="doc-biblioref">Box 2006</a>)</span>.</p>
<p>Suppose we want to maximize the number of baby rabbits. We think that adult male rabbits and adult female rabbits could affect the yield of baby rabbits. We plan to test the effect of different combinations of male and female rabbits.</p>
<p>Here is the experiment, using the “One-variable-at-a-time” method.</p>
<p><img src="figures/OVAT-fig-03.PNG" class="img-fluid"></p>
<p>This example illustrates one of the problems with the OVAT method: it misses important interactions. An interaction is when the effect of one factor (male rabbits) depends on the level of another factor (female rabbits).</p>
</section>
<section id="are-interactions-important-in-medicine-and-in-biological-research" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="are-interactions-important-in-medicine-and-in-biological-research"><span class="header-section-number">15.3</span> Are interactions important in medicine and in biological research?</h2>
<p>Does every treatment work for every patient? Clearly no. The effect of a treatment in a given patient can depend on the patient’s genetics, age, disease severity, and many other factors. Because the effect of a treatment is different for different genetics, age, and so on, there is an interaction. The entire field of personalized medicine exists because there are important interactions; different people respond differently to the same drug. To make treatments more effective, we need to look at combinations of treatment with genetics, age, disease severity, and so on. We cannot look at only one variable at a time.</p>
<p>Look again at the experiment designs used for the baby rabbits and in Plan 1 for baking.</p>
<p><img src="figures/OVAT-fig-04.PNG" class="img-fluid"></p>
<p><img src="figures/OVAT-fig-05.PNG" class="img-fluid"></p>
<p>These two designs don’t examine the space of factor combinations efficiently. As we will see, both of these designs are examples of one-variable-at-a-time (“OVAT”) experiment designs. OVAT experiments are typically analyzed with t-tests. We will see shortly that OVAT has another problem: It makes very inefficient use of the number of samples, giving low power and poor p-values. Factorial designs can give much more information, and smaller p-values, for the same number of samples.</p>
</section>
<section id="factorial-experiment-design-an-alternative-to-ovat" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="factorial-experiment-design-an-alternative-to-ovat"><span class="header-section-number">15.4</span> Factorial experiment design: an alternative to OVAT</h2>
<p>Let’s look at an example of a factorial design. This example is also from George Box, “Improving almost anything”.</p>
<p>“Engineers (at the bearing manufacturer SKF) wanted to find the effect of changing to a less expensive ‘cage’ design.”</p>
<p>“The results were assessed by an accelerated life test. … The runs were expensive because they needed to be made on an actual production line and the experimenters were planning to make four runs with the standard cage and four with the modified cage.”</p>
<p>Notice that this is a very typical experiment design: One factor, 2 treatment conditions (levels), 4 runs each, total 8 runs.</p>
<p>“Christer asked if there were other factors they would like to test. They said there were, but that making added runs would exceed their budget. Christer showed them how they could test two additional factors ‘for free’ – without increasing the number of runs and without reducing the accuracy of their estimate of the cage effect. In this arrangement, called a 2<sup>3</sup> factorial design, each of the three factors would be run at two levels and all the eight possible combinations included. The various combinations can conveniently be shown as the vertices of a cube …”</p>
<p>“Figure 2(b) [the cube plot below] shows a 2<sup>3</sup> factorial experiment reported by Christer Hellstrand…”</p>
<p><img src="figures/OVAT-fig-06.PNG" class="img-fluid"></p>
<p>“In each case, the standard condition is indicated by a minus sign and the modified condition by a plus sign. The factors changed were heat treatment, outer ring osculation, and cage design. The numbers show the relative lengths of lives of the bearings. If you look at [the cube plot], you can see that the choice of cage design did not make a lot of difference.”</p>
<p>“But, if you average the pairs of numbers for cage design, you get the [table below], which shows what the two other factors did. … It led to the extraordinary discovery that, in this particular application, the life of a bearing can be increased fivefold if the two factor(s) outer ring osculation and inner ring heat treatments are increased <em>together</em>. This and similar experiments have saved tens of millions of dollars.”</p>
<div class="cell">
<div id="tbl-bearing-life" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-bearing-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15.1: Bearing life versus heat and osculation
</figcaption>
<div aria-describedby="tbl-bearing-life-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table cell caption-top table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Osculation −</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Osculation +</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Heat −</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Heat +</td>
<td style="text-align: right;">23</td>
<td style="text-align: right; font-weight: bold;">106</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>“Remembering that bearings like this one have been made for decades, it is at first surprising that it could take so long to discover so important an improvement. A likely explanation is that, because most engineers have, until recently, employed only one factor at a time experimentation, interaction effects have been missed.”</p>
<p>“There are hundreds of thousands of engineers in this country, and even if the 2<sup>3</sup> factorial was the only kind of design they ever used, and even if the only method of analysis that was employed was to eyeball the data, this alone could have an enormous impact on experimental efficiency, the rate of innovation, and competitive position.”</p>
<p>This experiment gives an example of an interaction: if both Heat and Osculation are changed at the same time, the effect is much more than just the sum of increasing each of them one at a time.</p>
<p>Further, the variable that the engineers first thought of testing, the Cage design, had very little effect compared to the Heat and Osculation interaction. If the OVAT design had been used, neither Heat nor Osculation would have been tested.</p>
<p>I recommend you get a copy of Box’s book “Improving Almost Anything” <span class="citation" data-cites="box2006">(<a href="references.html#ref-box2006" role="doc-biblioref">Box 2006</a>)</span>. You will find it both fun and informative reading.</p>
<p>Now let’s apply these concepts to a typical biology experiment.</p>
</section>
<section id="example-experiment-design-for-3-factors" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="example-experiment-design-for-3-factors"><span class="header-section-number">15.5</span> Example: experiment design for 3 factors</h2>
<p>Suppose you are planning an experiment. You are considering changing the temperature, the salt concentration, or the buffer to improve the results (for example, maximizing the yield). How can you efficiently find a good combination of the 3 factors?</p>
<p><strong>Plan 1.</strong> Here is one possible plan to test the effects of the 3 variables. We will run 16 batches. The table shows the Temperature, Buffer, and Salt for each of the 16 batches in Plan 1. Notice that this design is following the OVAT rule: only change one variable at a time.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Batch</th>
<th>Treatment combination</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>All factors at level 0</td>
</tr>
<tr class="even">
<td>2</td>
<td>All factors at level 0</td>
</tr>
<tr class="odd">
<td>3</td>
<td>All factors at level 0</td>
</tr>
<tr class="even">
<td>4</td>
<td>All factors at level 0</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Temp level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>6</td>
<td>Temp level 1. Other factors at 0.</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Temp level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>8</td>
<td>Temp level 1. Other factors at 0.</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Buffer level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>10</td>
<td>Buffer level 1. Other factors at 0.</td>
</tr>
<tr class="odd">
<td>11</td>
<td>Buffer level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>12</td>
<td>Buffer level 1. Other factors at 0.</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Salt level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>14</td>
<td>Salt level 1. Other factors at 0.</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Salt level 1. Other factors at 0.</td>
</tr>
<tr class="even">
<td>16</td>
<td>Salt level 1. Other factors at 0.</td>
</tr>
</tbody>
</table>
<p>Here is a geometric view of the 16 batches using the OVAT experiment design.</p>
<p><img src="figures/OVAT-fig-07.PNG" class="img-fluid"></p>
<p>Here is Plan 1 again, now showing explicitly the combinations that are not tested. Does this remind you of the baby rabbit OVAT design? In this OVAT design, many combinations are not tested.</p>
<p><img src="figures/OVAT-fig-08.PNG" class="img-fluid"></p>
<p><strong>Plan 2.</strong> Here is an alternative plan for the 16 batches. This is the factorial design. Notice that every combination of factor levels is tested.</p>
<p><img src="figures/OVAT-fig-09.PNG" class="img-fluid"></p>
<p>Here is the table showing the treatment assignments for each batch in the factorial design. For the factorial design, a zero, 0, indicates that the variable is at the current level. A one, 1, indicates that the variable is at the alternative level.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>(ii) Factorial Design</strong></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Batch</td>
<td>Temperature</td>
<td>Buffer</td>
<td>Salt</td>
</tr>
<tr class="even">
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>4</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>5</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>6</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>7</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>8</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>9</td>
<td>1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>10</td>
<td>1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>11</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>12</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>13</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>14</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>15</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>16</td>
<td>1</td>
<td>1</td>
<td>1</td>
</tr>
</tbody>
</table>
<p>With Plan 1 (OVAT) we cannot discover interactions. To do that, we would need to do more batches.</p>
<p>With Plan 2 (factorial design) we can discover interactions. With Plan 2 we can examine all the combinations of the variables.</p>
</section>
<section id="factorial-designs-have-more-power-than-ovat-designs" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="factorial-designs-have-more-power-than-ovat-designs"><span class="header-section-number">15.6</span> Factorial designs have more power than OVAT designs</h2>
<p>Factorial designs have another important advantage over OVAT designs: factorial designs have more power to detect effects. To see why, let’s compare the two designs side-by-side for the 3-factor experiment.</p>
<p><strong>Table 1.</strong> Comparison of (i) a one-variable-at-a-time (OVAT) design to (ii) a factorial design to study 3 variables in 16 batches. For the factorial design, a zero, 0, indicates that the variable is at the current level. A one, 1, indicates that the variable is at the alternative level.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table caption-top table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
(i) One variable at a time (OVAT)
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px; font-weight: bold;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
(ii) Factorial Design
</div></th>
</tr>
<tr class="even">
<th style="text-align: right;" data-quarto-table-cell-role="th">Batch</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Treatment combination</th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Batch</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Temperature</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Buffer</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Salt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">All factors at level 0</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">All factors at level 0</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">All factors at level 0</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">All factors at level 0</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Temp level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Temp level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Temp level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Temp level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Buffer level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Buffer level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Buffer level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Buffer level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Salt level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">Salt level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">Salt level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: left;">Salt level 1</td>
<td style="text-align: left; border-left: 1px solid; border-right: 1px solid;"></td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Notice that, in the OVAT design, we only observe the alternative (1) level of each variable in 4 of the 16 batches. Having only 4 observations limits our power to detect the effects of a variable. Can we observe the alternative level of each variable 8 times, instead of 4 (thus increasing the effective sample size), but still use only 16 batches?</p>
<p>The right-hand side of Table 1 shows the alternative experiment, using a factorial design. For this factorial design, the 16 batches use all possible combinations of the 3 variables. With 3 variables either present or absent, we have 2<sup>3</sup> = 8 combinations. Including a replicate gives us 2×8 = 16 batches. Each row in the factorial design in Table 1 gives the variables used in one batch.</p>
<p>For example, for Batch 1, 0 indicates that temperature, buffer, and salt are all at the current level. For Batch 3, the 1 indicates that temperature is at the alternative level, while 0 indicates buffer and salt are at the current level. Rows 9 to 16 indicate that combinations of variables are used; in rows 15 and 16, the 1 indicates that temperature, buffer, and salt are all at the alternative level. Having more than one variable at alternative levels in a batch allows us to observe interactions between the variables in their effect on yield.</p>
<p>How does the factorial design compare to the OVAT design? Both designs use 16 batches. In the factorial design the effect of each variable is observed 8 times. In the OVAT design the effect of each variable is observed only 4 times. By changing from OVAT to the factorial design, we have doubled the number of observations of the effect of each variable; we have doubled the effective sample size and increased our power to detect the effect of each variable, without increasing the total number of batches. The factorial design also tells us about interactions, which are impossible to detect in the OVAT design. With additional experiments, OVAT might or might not eventually detect interactions.</p>
</section>
<section id="what-about-replication-in-ovat-versus-factorial-designs" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="what-about-replication-in-ovat-versus-factorial-designs"><span class="header-section-number">15.7</span> What about replication in OVAT versus factorial designs?</h2>
<p>If we compare the OVAT and factorial designs for the previous experiment, we see that the OVAT design has 4 replicates of each treatment combination, while the factorial design had 2 replicates of each treatment combination. Is this a reason for concern?</p>
<p>In some circumstances, yes. If the treatment assignments become confused (for example, by pipetting errors), or if specimens are likely to get the wrong treatment, then the error might be detected more readily in an OVAT design.</p>
<p><img src="figures/OVAT-fig-08.PNG" class="img-fluid"></p>
<p><img src="figures/OVAT-fig-09.PNG" class="img-fluid"></p>
<p>However, the factorial design may still be preferable to OVAT even with labeling errors. In the OVAT design, the alternative level of each factor is only tested 4 times. In the factorial design, the alternative level is tested 8 times. By testing 8 times instead of only 4, the factorial design can provide greater ability to detect an incorrectly treated or mis-labeled specimen.</p>
</section>
<section id="statistical-analysis-of-factorial-designs" class="level2" data-number="15.8">
<h2 data-number="15.8" class="anchored" data-anchor-id="statistical-analysis-of-factorial-designs"><span class="header-section-number">15.8</span> Statistical analysis of factorial designs</h2>
<p>Hypothesis tests for factorial designs are not always necessary. In the ball-bearing example, visual inspection of the results was sufficient to show the large interaction effect and to determine which combination gave the best yield.</p>
<p><img src="figures/OVAT-fig-06.PNG" class="img-fluid"></p>
<p>When we want a p-value, we use analysis of variance or multiple regression to test the treatment effects and interactions. In Part 2 of the book, the chapters on multiway ANOVA, multiple regression, and interactions give more details of this type of analysis.</p>
<p>Here I’ll show a multiple regression analysis. In this example, I’ll assume there are no interactions. See the chapters in Part 2 on ANOVA and regression with interactions for example interaction analyses.</p>
<p>Suppose we have the following data for the salt, buffer, and temperature example, including the yield.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>temperature <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"Low"</span>,<span class="st">"High"</span>,<span class="st">"High"</span>), <span class="dv">4</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>salt.conc   <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"High"</span>,<span class="st">"Low"</span>,<span class="st">"High"</span>), <span class="dv">4</span>))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>buffer.type <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>), <span class="dv">2</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>yield       <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">7.88</span>, <span class="fl">6.54</span>, <span class="fl">16.12</span>, <span class="fl">11.14</span>, <span class="fl">9.26</span>, <span class="fl">10.43</span>, <span class="fl">13.92</span>, <span class="fl">8.47</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>                 <span class="fl">7.63</span>, <span class="fl">6.11</span>, <span class="fl">15.45</span>, <span class="fl">11.72</span>, <span class="fl">9.80</span>,  <span class="fl">7.22</span>, <span class="fl">11.89</span>, <span class="fl">14.57</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>yield.data  <span class="ot">=</span> <span class="fu">data.frame</span>(temperature, salt.conc, buffer.type, yield)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>yield.data</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   temperature salt.conc buffer.type yield
1          Low       Low           A  7.88
2          Low      High           A  6.54
3         High       Low           A 16.12
4         High      High           A 11.14
5          Low       Low           B  9.26
6          Low      High           B 10.43
7         High       Low           B 13.92
8         High      High           B  8.47
9          Low       Low           A  7.63
10         Low      High           A  6.11
11        High       Low           A 15.45
12        High      High           A 11.72
13         Low       Low           B  9.80
14         Low      High           B  7.22
15        High       Low           B 11.89
16        High      High           B 14.57</code></pre>
</div>
</div>
<p>The R function <code>plot.design</code> provides a quick display of the mean yield for each treatment level. Note that, in <code>plot.design</code>, the response variable is numeric, and the explanatory factors are text (e.g., “low” and “high”).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph the results using plot.design.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.design</span>(yield <span class="sc">~</span> buffer.type <span class="sc">+</span> temperature <span class="sc">+</span> salt.conc,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> yield.data, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">14</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ch15-avoid-OVAT_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>plot.design</code> figure indicates the following.</p>
<ul>
<li>There is a large effect of temperature on yield. High temperature gives better yield.</li>
<li>There is a moderate effect of salt concentration on yield. Low salt gives better yield.</li>
<li>There is very little effect of buffer type on yield.</li>
</ul>
<p>Here is the regression analysis and the output.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>yield.data.lm <span class="ot">=</span> <span class="fu">lm</span>(yield <span class="sc">~</span> buffer.type <span class="sc">+</span> temperature <span class="sc">+</span> salt.conc, <span class="at">data =</span> yield.data)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yield.data.lm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = yield ~ buffer.type + temperature + salt.conc, data = yield.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.6412 -0.8784 -0.1250  0.8262  3.1200 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     11.7400     0.9883  11.879 5.41e-08 ***
buffer.typeB     0.3712     0.9883   0.376 0.713729    
temperatureLow  -4.8013     0.9883  -4.858 0.000393 ***
salt.concLow     1.9688     0.9883   1.992 0.069610 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.977 on 12 degrees of freedom
Multiple R-squared:  0.6978,    Adjusted R-squared:  0.6223 
F-statistic: 9.237 on 3 and 12 DF,  p-value: 0.001921</code></pre>
</div>
</div>
<p>The regression analysis gives the same results as the plot, and provides p-values and quantification of the effects.</p>
<ul>
<li>Temperature has a significant effect on yield, p=0.00039. High temperature increases yield by 4.8.</li>
<li>Salt concentration has a near significant effect on yield, p=0.0696. For the purpose of future experiments, I would use the low concentration. Low salt concentration appears to increase yield by about 1.97.</li>
<li>Buffer type does not have a significant effect on yield, p=0.71. If one of the buffers is cheaper or easier to work with, we might make the selection on that basis.</li>
</ul>
<p>This experiment has provided a lot of information with a relatively small number of batches.</p>
</section>
<section id="when-may-ovat-be-preferable" class="level2" data-number="15.9">
<h2 data-number="15.9" class="anchored" data-anchor-id="when-may-ovat-be-preferable"><span class="header-section-number">15.9</span> When may OVAT be preferable?</h2>
<p>There are circumstances where OVAT may be preferable. As noted above, if the treatment assignments become confused (for example, by pipetting errors) the confusion may be detected more readily in an OVAT design. If combinations of variables may be dangerous or lethal, OVAT is preferable. In some cases, such as re-programming a robot to create a factorial layout, the logistics of implementing factorial design may be difficult. However, OVAT design should be selected when such concerns exist for your experiment, rather than by default.</p>
</section>
<section id="recommended-youtube-videos" class="level2" data-number="15.10">
<h2 data-number="15.10" class="anchored" data-anchor-id="recommended-youtube-videos"><span class="header-section-number">15.10</span> Recommended YouTube videos</h2>
<p>Kevin Dunn. “Process improvement using data”</p>
<p>See the attached Excel file “Factorial design recommended videos” for the video titles and duration.</p>
</section>
<section id="recommended-free-textbook-pdf" class="level2" data-number="15.11">
<h2 data-number="15.11" class="anchored" data-anchor-id="recommended-free-textbook-pdf"><span class="header-section-number">15.11</span> Recommended free textbook PDF</h2>
<p>A free PDF of the text “A First Course in Design and Analysis of Experiments” by Gary Oehlert is available at this website: <a href="http://users.stat.umn.edu/~gary/Book.html" class="uri">http://users.stat.umn.edu/~gary/Book.html</a></p>


<!-- -->

<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-box2006" class="csl-entry" role="listitem">
Box, George E. P. 2006. <em>Improving Almost Anything: Ideas and Essays</em>. Revised. John Wiley &amp; Sons.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/ch14-two-primary-analyses.html" class="pagination-link" aria-label="Use two primary analyses each with alpha 0.025 instead of one with 0.05">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Use two primary analyses each with alpha 0.025 instead of one with 0.05</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/ch16-rescue-factorial.html" class="pagination-link" aria-label="Rescue failed experiments using fractional factorial designs">
        <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Rescue failed experiments using fractional factorial designs</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Avoid one-variable-at-a-time experiments. Use factorial experiment design."</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: setup</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| include: false</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(kableExtra)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>You have likely heard the advice, "Hold everything constant, change one thing at a time"? This is the one-variable-at-a-time (OVAT) approach.</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>As you will see in this chapter, OVAT is often a very inefficient and ineffective way to perform an experiment. An alternative to OVAT is factorial experiment design, which you may have encountered as Design of Experiments (DOE).</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>Compared to OVAT, factorial design of experiments has several advantages:</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Quickly and efficiently test the effects of multiple factors.</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Increase power.</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Get better p-values.</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Detect interactions missed by OVAT.</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>Factorial designs provide more information with less work than OVAT experiments, as we'll see. Let's start with a familiar example: baking cookies.</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="fu">## An intuitive view of experiment design: baking cookies</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>Suppose we are baking cookies. We want to maximize the yield of good cookies. We think that the time in the oven and the temperature in the oven could affect the yield. We plan to bake 4 batches using different combinations of time and temperature in the oven.</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>**Plan 1.** Here is one possible plan for the 4 batches.</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-01.PNG)</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>The x axis is time in the oven. 0 is a short time in the oven, and 1 is a long time.</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>The y axis is temperature in the oven. 0 is a low temperature in the oven, and 1 is a high temperature.</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>The table shows the time and temperature for each batch.</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Batch number <span class="pp">|</span> Time <span class="pp">|</span> Temperature <span class="pp">|</span></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>Does Plan 1 seem like a good way to design the experiment? Why or why not? Clearly, it seems pretty inefficient and uninformative to test the short time and low temperature (0,0) combination twice, but not to test the short time and high temperature (1,0) combination at all.</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>**Plan 2.** Here is an alternative plan for the 4 batches.</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-02.PNG)</span></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>The table shows the time and temperature for each batch.</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Batch number <span class="pp">|</span> Time <span class="pp">|</span> Temperature <span class="pp">|</span></span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>Does Plan 2 look like a better plan?</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-66"><a href="#cb6-66" aria-hidden="true" tabindex="-1"></a><span class="fu">## The problems with "One variable at a time"</span></span>
<span id="cb6-67"><a href="#cb6-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-68"><a href="#cb6-68" aria-hidden="true" tabindex="-1"></a>So, what's wrong with one variable at a time? Let's look at an example of the OVAT method from the book "Improving Almost Anything" by George Box <span class="co">[</span><span class="ot">@box2006</span><span class="co">]</span>.</span>
<span id="cb6-69"><a href="#cb6-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-70"><a href="#cb6-70" aria-hidden="true" tabindex="-1"></a>Suppose we want to maximize the number of baby rabbits. We think that adult male rabbits and adult female rabbits could affect the yield of baby rabbits. We plan to test the effect of different combinations of male and female rabbits.</span>
<span id="cb6-71"><a href="#cb6-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-72"><a href="#cb6-72" aria-hidden="true" tabindex="-1"></a>Here is the experiment, using the "One-variable-at-a-time" method.</span>
<span id="cb6-73"><a href="#cb6-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-74"><a href="#cb6-74" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-03.PNG)</span></span>
<span id="cb6-75"><a href="#cb6-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-76"><a href="#cb6-76" aria-hidden="true" tabindex="-1"></a>This example illustrates one of the problems with the OVAT method: it misses important interactions. An interaction is when the effect of one factor (male rabbits) depends on the level of another factor (female rabbits).</span>
<span id="cb6-77"><a href="#cb6-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-78"><a href="#cb6-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## Are interactions important in medicine and in biological research?</span></span>
<span id="cb6-79"><a href="#cb6-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-80"><a href="#cb6-80" aria-hidden="true" tabindex="-1"></a>Does every treatment work for every patient? Clearly no. The effect of a treatment in a given patient can depend on the patient's genetics, age, disease severity, and many other factors. Because the effect of a treatment is different for different genetics, age, and so on, there is an interaction. The entire field of personalized medicine exists because there are important interactions; different people respond differently to the same drug. To make treatments more effective, we need to look at combinations of treatment with genetics, age, disease severity, and so on. We cannot look at only one variable at a time.</span>
<span id="cb6-81"><a href="#cb6-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-82"><a href="#cb6-82" aria-hidden="true" tabindex="-1"></a>Look again at the experiment designs used for the baby rabbits and in Plan 1 for baking.</span>
<span id="cb6-83"><a href="#cb6-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-84"><a href="#cb6-84" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-04.PNG)</span></span>
<span id="cb6-85"><a href="#cb6-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-86"><a href="#cb6-86" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-05.PNG)</span></span>
<span id="cb6-87"><a href="#cb6-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-88"><a href="#cb6-88" aria-hidden="true" tabindex="-1"></a>These two designs don't examine the space of factor combinations efficiently. As we will see, both of these designs are examples of one-variable-at-a-time ("OVAT") experiment designs. OVAT experiments are typically analyzed with t-tests. We will see shortly that OVAT has another problem: It makes very inefficient use of the number of samples, giving low power and poor p-values. Factorial designs can give much more information, and smaller p-values, for the same number of samples.</span>
<span id="cb6-89"><a href="#cb6-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-90"><a href="#cb6-90" aria-hidden="true" tabindex="-1"></a><span class="fu">## Factorial experiment design: an alternative to OVAT</span></span>
<span id="cb6-91"><a href="#cb6-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-92"><a href="#cb6-92" aria-hidden="true" tabindex="-1"></a>Let's look at an example of a factorial design. This example is also from George Box, "Improving almost anything".</span>
<span id="cb6-93"><a href="#cb6-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-94"><a href="#cb6-94" aria-hidden="true" tabindex="-1"></a>"Engineers (at the bearing manufacturer SKF) wanted to find the effect of changing to a less expensive 'cage' design."</span>
<span id="cb6-95"><a href="#cb6-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-96"><a href="#cb6-96" aria-hidden="true" tabindex="-1"></a>"The results were assessed by an accelerated life test. … The runs were expensive because they needed to be made on an actual production line and the experimenters were planning to make four runs with the standard cage and four with the modified cage."</span>
<span id="cb6-97"><a href="#cb6-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-98"><a href="#cb6-98" aria-hidden="true" tabindex="-1"></a>Notice that this is a very typical experiment design: One factor, 2 treatment conditions (levels), 4 runs each, total 8 runs.</span>
<span id="cb6-99"><a href="#cb6-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-100"><a href="#cb6-100" aria-hidden="true" tabindex="-1"></a>"Christer asked if there were other factors they would like to test. They said there were, but that making added runs would exceed their budget. Christer showed them how they could test two additional factors 'for free' – without increasing the number of runs and without reducing the accuracy of their estimate of the cage effect. In this arrangement, called a 2^3^ factorial design, each of the three factors would be run at two levels and all the eight possible combinations included. The various combinations can conveniently be shown as the vertices of a cube ..."</span>
<span id="cb6-101"><a href="#cb6-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-102"><a href="#cb6-102" aria-hidden="true" tabindex="-1"></a>"Figure 2(b) <span class="co">[</span><span class="ot">the cube plot below</span><span class="co">]</span> shows a 2^3^ factorial experiment reported by Christer Hellstrand…"</span>
<span id="cb6-103"><a href="#cb6-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-104"><a href="#cb6-104" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-06.PNG)</span></span>
<span id="cb6-105"><a href="#cb6-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-106"><a href="#cb6-106" aria-hidden="true" tabindex="-1"></a>"In each case, the standard condition is indicated by a minus sign and the modified condition by a plus sign. The factors changed were heat treatment, outer ring osculation, and cage design. The numbers show the relative lengths of lives of the bearings. If you look at <span class="co">[</span><span class="ot">the cube plot</span><span class="co">]</span>, you can see that the choice of cage design did not make a lot of difference."</span>
<span id="cb6-107"><a href="#cb6-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-108"><a href="#cb6-108" aria-hidden="true" tabindex="-1"></a>"But, if you average the pairs of numbers for cage design, you get the <span class="co">[</span><span class="ot">table below</span><span class="co">]</span>, which shows what the two other factors did. … It led to the extraordinary discovery that, in this particular application, the life of a bearing can be increased fivefold if the two factor(s) outer ring osculation and inner ring heat treatments are increased *together*. This and similar experiments have saved tens of millions of dollars."</span>
<span id="cb6-109"><a href="#cb6-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-112"><a href="#cb6-112" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-113"><a href="#cb6-113" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-114"><a href="#cb6-114" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb6-115"><a href="#cb6-115" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-116"><a href="#cb6-116" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-bearing-life</span></span>
<span id="cb6-117"><a href="#cb6-117" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Bearing life versus heat and osculation"</span></span>
<span id="cb6-118"><a href="#cb6-118" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb6-119"><a href="#cb6-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-120"><a href="#cb6-120" aria-hidden="true" tabindex="-1"></a>bearing <span class="ot">=</span> <span class="fu">data.frame</span>(</span>
<span id="cb6-121"><a href="#cb6-121" aria-hidden="true" tabindex="-1"></a>  <span class="at">Heat      =</span> <span class="fu">c</span>(<span class="st">"Heat −"</span>, <span class="st">"Heat +"</span>),</span>
<span id="cb6-122"><a href="#cb6-122" aria-hidden="true" tabindex="-1"></a>  <span class="at">Osc_minus =</span> <span class="fu">c</span>(<span class="dv">18</span>, <span class="dv">23</span>),</span>
<span id="cb6-123"><a href="#cb6-123" aria-hidden="true" tabindex="-1"></a>  <span class="at">Osc_plus  =</span> <span class="fu">c</span>(<span class="dv">21</span>, <span class="dv">106</span>)</span>
<span id="cb6-124"><a href="#cb6-124" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-125"><a href="#cb6-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-126"><a href="#cb6-126" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(bearing,</span>
<span id="cb6-127"><a href="#cb6-127" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">"Osculation −"</span>, <span class="st">"Osculation +"</span>),</span>
<span id="cb6-128"><a href="#cb6-128" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs  =</span> <span class="cn">TRUE</span>,</span>
<span id="cb6-129"><a href="#cb6-129" aria-hidden="true" tabindex="-1"></a>    <span class="at">linesep   =</span> <span class="st">""</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-130"><a href="#cb6-130" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">latex_options =</span> <span class="fu">c</span>(<span class="st">"hold_position"</span>),</span>
<span id="cb6-131"><a href="#cb6-131" aria-hidden="true" tabindex="-1"></a>                <span class="at">full_width    =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-132"><a href="#cb6-132" aria-hidden="true" tabindex="-1"></a>                <span class="at">position      =</span> <span class="st">"left"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-133"><a href="#cb6-133" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">3</span>, <span class="at">bold =</span> <span class="fu">c</span>(<span class="cn">FALSE</span>, <span class="cn">TRUE</span>))</span>
<span id="cb6-134"><a href="#cb6-134" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-135"><a href="#cb6-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-136"><a href="#cb6-136" aria-hidden="true" tabindex="-1"></a>"Remembering that bearings like this one have been made for decades, it is at first surprising that it could take so long to discover so important an improvement. A likely explanation is that, because most engineers have, until recently, employed only one factor at a time experimentation, interaction effects have been missed."</span>
<span id="cb6-137"><a href="#cb6-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-138"><a href="#cb6-138" aria-hidden="true" tabindex="-1"></a>"There are hundreds of thousands of engineers in this country, and even if the 2^3^ factorial was the only kind of design they ever used, and even if the only method of analysis that was employed was to eyeball the data, this alone could have an enormous impact on experimental efficiency, the rate of innovation, and competitive position."</span>
<span id="cb6-139"><a href="#cb6-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-140"><a href="#cb6-140" aria-hidden="true" tabindex="-1"></a>This experiment gives an example of an interaction: if both Heat and Osculation are changed at the same time, the effect is much more than just the sum of increasing each of them one at a time.</span>
<span id="cb6-141"><a href="#cb6-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-142"><a href="#cb6-142" aria-hidden="true" tabindex="-1"></a>Further, the variable that the engineers first thought of testing, the Cage design, had very little effect compared to the Heat and Osculation interaction. If the OVAT design had been used, neither Heat nor Osculation would have been tested.</span>
<span id="cb6-143"><a href="#cb6-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-144"><a href="#cb6-144" aria-hidden="true" tabindex="-1"></a>I recommend you get a copy of Box's book "Improving Almost Anything" <span class="co">[</span><span class="ot">@box2006</span><span class="co">]</span>. You will find it both fun and informative reading.</span>
<span id="cb6-145"><a href="#cb6-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-146"><a href="#cb6-146" aria-hidden="true" tabindex="-1"></a>Now let's apply these concepts to a typical biology experiment.</span>
<span id="cb6-147"><a href="#cb6-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-148"><a href="#cb6-148" aria-hidden="true" tabindex="-1"></a><span class="fu">## Example: experiment design for 3 factors</span></span>
<span id="cb6-149"><a href="#cb6-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-150"><a href="#cb6-150" aria-hidden="true" tabindex="-1"></a>Suppose you are planning an experiment. You are considering changing the temperature, the salt concentration, or the buffer to improve the results (for example, maximizing the yield). How can you efficiently find a good combination of the 3 factors?</span>
<span id="cb6-151"><a href="#cb6-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-152"><a href="#cb6-152" aria-hidden="true" tabindex="-1"></a>**Plan 1.** Here is one possible plan to test the effects of the 3 variables. We will run 16 batches. The table shows the Temperature, Buffer, and Salt for each of the 16 batches in Plan 1. Notice that this design is following the OVAT rule: only change one variable at a time.</span>
<span id="cb6-153"><a href="#cb6-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-154"><a href="#cb6-154" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Batch <span class="pp">|</span> Treatment combination <span class="pp">|</span></span>
<span id="cb6-155"><a href="#cb6-155" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|</span></span>
<span id="cb6-156"><a href="#cb6-156" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> All factors at level 0 <span class="pp">|</span></span>
<span id="cb6-157"><a href="#cb6-157" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> All factors at level 0 <span class="pp">|</span></span>
<span id="cb6-158"><a href="#cb6-158" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> All factors at level 0 <span class="pp">|</span></span>
<span id="cb6-159"><a href="#cb6-159" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> All factors at level 0 <span class="pp">|</span></span>
<span id="cb6-160"><a href="#cb6-160" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> Temp level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-161"><a href="#cb6-161" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> Temp level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-162"><a href="#cb6-162" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 7 <span class="pp">|</span> Temp level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-163"><a href="#cb6-163" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 8 <span class="pp">|</span> Temp level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-164"><a href="#cb6-164" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 9 <span class="pp">|</span> Buffer level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-165"><a href="#cb6-165" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 10 <span class="pp">|</span> Buffer level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-166"><a href="#cb6-166" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 11 <span class="pp">|</span> Buffer level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-167"><a href="#cb6-167" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 12 <span class="pp">|</span> Buffer level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-168"><a href="#cb6-168" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 13 <span class="pp">|</span> Salt level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-169"><a href="#cb6-169" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 14 <span class="pp">|</span> Salt level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-170"><a href="#cb6-170" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 15 <span class="pp">|</span> Salt level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-171"><a href="#cb6-171" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 16 <span class="pp">|</span> Salt level 1. Other factors at 0. <span class="pp">|</span></span>
<span id="cb6-172"><a href="#cb6-172" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-173"><a href="#cb6-173" aria-hidden="true" tabindex="-1"></a>Here is a geometric view of the 16 batches using the OVAT experiment design.</span>
<span id="cb6-174"><a href="#cb6-174" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-175"><a href="#cb6-175" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-07.PNG)</span></span>
<span id="cb6-176"><a href="#cb6-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-177"><a href="#cb6-177" aria-hidden="true" tabindex="-1"></a>Here is Plan 1 again, now showing explicitly the combinations that are not tested. Does this remind you of the baby rabbit OVAT design? In this OVAT design, many combinations are not tested.</span>
<span id="cb6-178"><a href="#cb6-178" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-179"><a href="#cb6-179" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-08.PNG)</span></span>
<span id="cb6-180"><a href="#cb6-180" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-181"><a href="#cb6-181" aria-hidden="true" tabindex="-1"></a>**Plan 2.** Here is an alternative plan for the 16 batches. This is the factorial design. Notice that every combination of factor levels is tested.</span>
<span id="cb6-182"><a href="#cb6-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-183"><a href="#cb6-183" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-09.PNG)</span></span>
<span id="cb6-184"><a href="#cb6-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-185"><a href="#cb6-185" aria-hidden="true" tabindex="-1"></a>Here is the table showing the treatment assignments for each batch in the factorial design. For the factorial design, a zero, 0, indicates that the variable is at the current level. A one, 1, indicates that the variable is at the alternative level.</span>
<span id="cb6-186"><a href="#cb6-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-187"><a href="#cb6-187" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **(ii) Factorial Design** <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span> <span class="pp">|</span></span>
<span id="cb6-188"><a href="#cb6-188" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|---|</span></span>
<span id="cb6-189"><a href="#cb6-189" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Batch <span class="pp">|</span> Temperature <span class="pp">|</span> Buffer <span class="pp">|</span> Salt <span class="pp">|</span></span>
<span id="cb6-190"><a href="#cb6-190" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-191"><a href="#cb6-191" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 2 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-192"><a href="#cb6-192" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-193"><a href="#cb6-193" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 4 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-194"><a href="#cb6-194" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 5 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-195"><a href="#cb6-195" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 6 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-196"><a href="#cb6-196" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 7 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-197"><a href="#cb6-197" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 8 <span class="pp">|</span> 0 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-198"><a href="#cb6-198" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 9 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-199"><a href="#cb6-199" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 10 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span></span>
<span id="cb6-200"><a href="#cb6-200" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 11 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-201"><a href="#cb6-201" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 12 <span class="pp">|</span> 1 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-202"><a href="#cb6-202" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 13 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-203"><a href="#cb6-203" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 14 <span class="pp">|</span> 0 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-204"><a href="#cb6-204" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 15 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-205"><a href="#cb6-205" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 16 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span> 1 <span class="pp">|</span></span>
<span id="cb6-206"><a href="#cb6-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-207"><a href="#cb6-207" aria-hidden="true" tabindex="-1"></a>With Plan 1 (OVAT) we cannot discover interactions. To do that, we would need to do more batches.</span>
<span id="cb6-208"><a href="#cb6-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-209"><a href="#cb6-209" aria-hidden="true" tabindex="-1"></a>With Plan 2 (factorial design) we can discover interactions. With Plan 2 we can examine all the combinations of the variables.</span>
<span id="cb6-210"><a href="#cb6-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-211"><a href="#cb6-211" aria-hidden="true" tabindex="-1"></a><span class="fu">## Factorial designs have more power than OVAT designs</span></span>
<span id="cb6-212"><a href="#cb6-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-213"><a href="#cb6-213" aria-hidden="true" tabindex="-1"></a>Factorial designs have another important advantage over OVAT designs: factorial designs have more power to detect effects. To see why, let's compare the two designs side-by-side for the 3-factor experiment.</span>
<span id="cb6-214"><a href="#cb6-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-215"><a href="#cb6-215" aria-hidden="true" tabindex="-1"></a>**Table 1.** Comparison of (i) a one-variable-at-a-time (OVAT) design to (ii) a factorial design to study 3 variables in 16 batches. For the factorial design, a zero, 0, indicates that the variable is at the current level. A one, 1, indicates that the variable is at the alternative level.</span>
<span id="cb6-216"><a href="#cb6-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-219"><a href="#cb6-219" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-220"><a href="#cb6-220" aria-hidden="true" tabindex="-1"></a><span class="co">#| echo: false</span></span>
<span id="cb6-221"><a href="#cb6-221" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb6-222"><a href="#cb6-222" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb6-223"><a href="#cb6-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-224"><a href="#cb6-224" aria-hidden="true" tabindex="-1"></a>tbl1 <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">Batch1 =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>,</span>
<span id="cb6-225"><a href="#cb6-225" aria-hidden="true" tabindex="-1"></a><span class="at">Treatment =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="st">"All factors at level 0"</span>, <span class="dv">4</span>),</span>
<span id="cb6-226"><a href="#cb6-226" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"Temp level 1"</span>,           <span class="dv">4</span>),</span>
<span id="cb6-227"><a href="#cb6-227" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"Buffer level 1"</span>,         <span class="dv">4</span>),</span>
<span id="cb6-228"><a href="#cb6-228" aria-hidden="true" tabindex="-1"></a>                <span class="fu">rep</span>(<span class="st">"Salt level 1"</span>,           <span class="dv">4</span>)),</span>
<span id="cb6-229"><a href="#cb6-229" aria-hidden="true" tabindex="-1"></a><span class="at">Sep         =</span> <span class="fu">rep</span>(<span class="st">""</span>, <span class="dv">16</span>),</span>
<span id="cb6-230"><a href="#cb6-230" aria-hidden="true" tabindex="-1"></a><span class="at">Batch2      =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">16</span>,</span>
<span id="cb6-231"><a href="#cb6-231" aria-hidden="true" tabindex="-1"></a><span class="at">Temperature =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>, <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>, <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb6-232"><a href="#cb6-232" aria-hidden="true" tabindex="-1"></a><span class="at">Buffer      =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb6-233"><a href="#cb6-233" aria-hidden="true" tabindex="-1"></a><span class="at">Salt        =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>, <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>, <span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>, <span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb6-234"><a href="#cb6-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-235"><a href="#cb6-235" aria-hidden="true" tabindex="-1"></a><span class="fu">kbl</span>(tbl1,</span>
<span id="cb6-236"><a href="#cb6-236" aria-hidden="true" tabindex="-1"></a>    <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Batch"</span>, <span class="st">"Treatment combination"</span>, <span class="st">""</span>, <span class="st">"Batch"</span>, <span class="st">"Temperature"</span>, <span class="st">"Buffer"</span>, <span class="st">"Salt"</span>),</span>
<span id="cb6-237"><a href="#cb6-237" aria-hidden="true" tabindex="-1"></a>    <span class="at">align     =</span> <span class="fu">c</span>(<span class="st">"r"</span>, <span class="st">"l"</span>, <span class="st">"l"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>, <span class="st">"r"</span>),</span>
<span id="cb6-238"><a href="#cb6-238" aria-hidden="true" tabindex="-1"></a>    <span class="at">booktabs  =</span> <span class="cn">FALSE</span>,</span>
<span id="cb6-239"><a href="#cb6-239" aria-hidden="true" tabindex="-1"></a>    <span class="at">linesep   =</span> <span class="st">""</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-240"><a href="#cb6-240" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">"(i) One variable at a time (OVAT)"</span> <span class="ot">=</span> <span class="dv">2</span>,</span>
<span id="cb6-241"><a href="#cb6-241" aria-hidden="true" tabindex="-1"></a>                     <span class="st">" "</span>                                  <span class="ot">=</span> <span class="dv">1</span>,</span>
<span id="cb6-242"><a href="#cb6-242" aria-hidden="true" tabindex="-1"></a>                     <span class="st">"(ii) Factorial Design"</span>              <span class="ot">=</span> <span class="dv">4</span>),</span>
<span id="cb6-243"><a href="#cb6-243" aria-hidden="true" tabindex="-1"></a>                   <span class="at">bold =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-244"><a href="#cb6-244" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">full_width =</span> <span class="cn">FALSE</span>, <span class="at">position =</span> <span class="st">"left"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-245"><a href="#cb6-245" aria-hidden="true" tabindex="-1"></a>  <span class="fu">column_spec</span>(<span class="dv">3</span>, <span class="at">border_left =</span> <span class="cn">TRUE</span>, <span class="at">border_right =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-246"><a href="#cb6-246" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-247"><a href="#cb6-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-248"><a href="#cb6-248" aria-hidden="true" tabindex="-1"></a>Notice that, in the OVAT design, we only observe the alternative (1) level of each variable in 4 of the 16 batches. Having only 4 observations limits our power to detect the effects of a variable. Can we observe the alternative level of each variable 8 times, instead of 4 (thus increasing the effective sample size), but still use only 16 batches?</span>
<span id="cb6-249"><a href="#cb6-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-250"><a href="#cb6-250" aria-hidden="true" tabindex="-1"></a>The right-hand side of Table 1 shows the alternative experiment, using a factorial design. For this factorial design, the 16 batches use all possible combinations of the 3 variables. With 3 variables either present or absent, we have 2^3^ = 8 combinations. Including a replicate gives us 2×8 = 16 batches. Each row in the factorial design in Table 1 gives the variables used in one batch.</span>
<span id="cb6-251"><a href="#cb6-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-252"><a href="#cb6-252" aria-hidden="true" tabindex="-1"></a>For example, for Batch 1, 0 indicates that temperature, buffer, and salt are all at the current level. For Batch 3, the 1 indicates that temperature is at the alternative level, while 0 indicates buffer and salt are at the current level. Rows 9 to 16 indicate that combinations of variables are used; in rows 15 and 16, the 1 indicates that temperature, buffer, and salt are all at the alternative level. Having more than one variable at alternative levels in a batch allows us to observe interactions between the variables in their effect on yield.</span>
<span id="cb6-253"><a href="#cb6-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-254"><a href="#cb6-254" aria-hidden="true" tabindex="-1"></a>How does the factorial design compare to the OVAT design? Both designs use 16 batches. In the factorial design the effect of each variable is observed 8 times. In the OVAT design the effect of each variable is observed only 4 times. By changing from OVAT to the factorial design, we have doubled the number of observations of the effect of each variable; we have doubled the effective sample size and increased our power to detect the effect of each variable, without increasing the total number of batches. The factorial design also tells us about interactions, which are impossible to detect in the OVAT design. With additional experiments, OVAT might or might not eventually detect interactions.</span>
<span id="cb6-255"><a href="#cb6-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-256"><a href="#cb6-256" aria-hidden="true" tabindex="-1"></a><span class="fu">## What about replication in OVAT versus factorial designs?</span></span>
<span id="cb6-257"><a href="#cb6-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-258"><a href="#cb6-258" aria-hidden="true" tabindex="-1"></a>If we compare the OVAT and factorial designs for the previous experiment, we see that the OVAT design has 4 replicates of each treatment combination, while the factorial design had 2 replicates of each treatment combination. Is this a reason for concern?</span>
<span id="cb6-259"><a href="#cb6-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-260"><a href="#cb6-260" aria-hidden="true" tabindex="-1"></a>In some circumstances, yes. If the treatment assignments become confused (for example, by pipetting errors), or if specimens are likely to get the wrong treatment, then the error might be detected more readily in an OVAT design.</span>
<span id="cb6-261"><a href="#cb6-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-262"><a href="#cb6-262" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-08.PNG)</span></span>
<span id="cb6-263"><a href="#cb6-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-264"><a href="#cb6-264" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-09.PNG)</span></span>
<span id="cb6-265"><a href="#cb6-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-266"><a href="#cb6-266" aria-hidden="true" tabindex="-1"></a>However, the factorial design may still be preferable to OVAT even with labeling errors. In the OVAT design, the alternative level of each factor is only tested 4 times. In the factorial design, the alternative level is tested 8 times. By testing 8 times instead of only 4, the factorial design can provide greater ability to detect an incorrectly treated or mis-labeled specimen.</span>
<span id="cb6-267"><a href="#cb6-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-268"><a href="#cb6-268" aria-hidden="true" tabindex="-1"></a><span class="fu">## Statistical analysis of factorial designs</span></span>
<span id="cb6-269"><a href="#cb6-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-270"><a href="#cb6-270" aria-hidden="true" tabindex="-1"></a>Hypothesis tests for factorial designs are not always necessary. In the ball-bearing example, visual inspection of the results was sufficient to show the large interaction effect and to determine which combination gave the best yield.</span>
<span id="cb6-271"><a href="#cb6-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-272"><a href="#cb6-272" aria-hidden="true" tabindex="-1"></a><span class="al">![](figures/OVAT-fig-06.PNG)</span></span>
<span id="cb6-273"><a href="#cb6-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-274"><a href="#cb6-274" aria-hidden="true" tabindex="-1"></a>When we want a p-value, we use analysis of variance or multiple regression to test the treatment effects and interactions. In Part 2 of the book, the chapters on multiway ANOVA, multiple regression, and interactions give more details of this type of analysis.</span>
<span id="cb6-275"><a href="#cb6-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-276"><a href="#cb6-276" aria-hidden="true" tabindex="-1"></a>Here I'll show a multiple regression analysis. In this example, I'll assume there are no interactions. See the chapters in Part 2 on ANOVA and regression with interactions for example interaction analyses.</span>
<span id="cb6-277"><a href="#cb6-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-278"><a href="#cb6-278" aria-hidden="true" tabindex="-1"></a>Suppose we have the following data for the salt, buffer, and temperature example, including the yield.</span>
<span id="cb6-279"><a href="#cb6-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-282"><a href="#cb6-282" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-283"><a href="#cb6-283" aria-hidden="true" tabindex="-1"></a>temperature <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"Low"</span>,<span class="st">"High"</span>,<span class="st">"High"</span>), <span class="dv">4</span>))</span>
<span id="cb6-284"><a href="#cb6-284" aria-hidden="true" tabindex="-1"></a>salt.conc   <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Low"</span>,<span class="st">"High"</span>,<span class="st">"Low"</span>,<span class="st">"High"</span>), <span class="dv">4</span>))</span>
<span id="cb6-285"><a href="#cb6-285" aria-hidden="true" tabindex="-1"></a>buffer.type <span class="ot">=</span> <span class="fu">factor</span>(<span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"A"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>,<span class="st">"B"</span>), <span class="dv">2</span>))</span>
<span id="cb6-286"><a href="#cb6-286" aria-hidden="true" tabindex="-1"></a>yield       <span class="ot">=</span> <span class="fu">c</span>(<span class="fl">7.88</span>, <span class="fl">6.54</span>, <span class="fl">16.12</span>, <span class="fl">11.14</span>, <span class="fl">9.26</span>, <span class="fl">10.43</span>, <span class="fl">13.92</span>, <span class="fl">8.47</span>,</span>
<span id="cb6-287"><a href="#cb6-287" aria-hidden="true" tabindex="-1"></a>                 <span class="fl">7.63</span>, <span class="fl">6.11</span>, <span class="fl">15.45</span>, <span class="fl">11.72</span>, <span class="fl">9.80</span>,  <span class="fl">7.22</span>, <span class="fl">11.89</span>, <span class="fl">14.57</span>)</span>
<span id="cb6-288"><a href="#cb6-288" aria-hidden="true" tabindex="-1"></a>yield.data  <span class="ot">=</span> <span class="fu">data.frame</span>(temperature, salt.conc, buffer.type, yield)</span>
<span id="cb6-289"><a href="#cb6-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-290"><a href="#cb6-290" aria-hidden="true" tabindex="-1"></a>yield.data</span>
<span id="cb6-291"><a href="#cb6-291" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-292"><a href="#cb6-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-293"><a href="#cb6-293" aria-hidden="true" tabindex="-1"></a>The R function <span class="in">`plot.design`</span> provides a quick display of the mean yield for each treatment level. Note that, in <span class="in">`plot.design`</span>, the response variable is numeric, and the explanatory factors are text (e.g., "low" and "high").</span>
<span id="cb6-294"><a href="#cb6-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-297"><a href="#cb6-297" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-298"><a href="#cb6-298" aria-hidden="true" tabindex="-1"></a><span class="co"># Graph the results using plot.design.</span></span>
<span id="cb6-299"><a href="#cb6-299" aria-hidden="true" tabindex="-1"></a><span class="fu">plot.design</span>(yield <span class="sc">~</span> buffer.type <span class="sc">+</span> temperature <span class="sc">+</span> salt.conc,</span>
<span id="cb6-300"><a href="#cb6-300" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> yield.data, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">14</span>))</span>
<span id="cb6-301"><a href="#cb6-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-302"><a href="#cb6-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-303"><a href="#cb6-303" aria-hidden="true" tabindex="-1"></a>The <span class="in">`plot.design`</span> figure indicates the following.</span>
<span id="cb6-304"><a href="#cb6-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-305"><a href="#cb6-305" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is a large effect of temperature on yield. High temperature gives better yield.</span>
<span id="cb6-306"><a href="#cb6-306" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is a moderate effect of salt concentration on yield. Low salt gives better yield.</span>
<span id="cb6-307"><a href="#cb6-307" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>There is very little effect of buffer type on yield.</span>
<span id="cb6-308"><a href="#cb6-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-309"><a href="#cb6-309" aria-hidden="true" tabindex="-1"></a>Here is the regression analysis and the output.</span>
<span id="cb6-310"><a href="#cb6-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-313"><a href="#cb6-313" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-314"><a href="#cb6-314" aria-hidden="true" tabindex="-1"></a>yield.data.lm <span class="ot">=</span> <span class="fu">lm</span>(yield <span class="sc">~</span> buffer.type <span class="sc">+</span> temperature <span class="sc">+</span> salt.conc, <span class="at">data =</span> yield.data)</span>
<span id="cb6-315"><a href="#cb6-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-316"><a href="#cb6-316" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(yield.data.lm)</span>
<span id="cb6-317"><a href="#cb6-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb6-318"><a href="#cb6-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-319"><a href="#cb6-319" aria-hidden="true" tabindex="-1"></a>The regression analysis gives the same results as the plot, and provides p-values and quantification of the effects.</span>
<span id="cb6-320"><a href="#cb6-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-321"><a href="#cb6-321" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Temperature has a significant effect on yield, p=0.00039. High temperature increases yield by 4.8.</span>
<span id="cb6-322"><a href="#cb6-322" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Salt concentration has a near significant effect on yield, p=0.0696. For the purpose of future experiments, I would use the low concentration. Low salt concentration appears to increase yield by about 1.97.</span>
<span id="cb6-323"><a href="#cb6-323" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Buffer type does not have a significant effect on yield, p=0.71. If one of the buffers is cheaper or easier to work with, we might make the selection on that basis.</span>
<span id="cb6-324"><a href="#cb6-324" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-325"><a href="#cb6-325" aria-hidden="true" tabindex="-1"></a>This experiment has provided a lot of information with a relatively small number of batches.</span>
<span id="cb6-326"><a href="#cb6-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-327"><a href="#cb6-327" aria-hidden="true" tabindex="-1"></a><span class="fu">## When may OVAT be preferable?</span></span>
<span id="cb6-328"><a href="#cb6-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-329"><a href="#cb6-329" aria-hidden="true" tabindex="-1"></a>There are circumstances where OVAT may be preferable. As noted above, if the treatment assignments become confused (for example, by pipetting errors) the confusion may be detected more readily in an OVAT design. If combinations of variables may be dangerous or lethal, OVAT is preferable. In some cases, such as re-programming a robot to create a factorial layout, the logistics of implementing factorial design may be difficult. However, OVAT design should be selected when such concerns exist for your experiment, rather than by default.</span>
<span id="cb6-330"><a href="#cb6-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-331"><a href="#cb6-331" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommended YouTube videos</span></span>
<span id="cb6-332"><a href="#cb6-332" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-333"><a href="#cb6-333" aria-hidden="true" tabindex="-1"></a>Kevin Dunn. "Process improvement using data"</span>
<span id="cb6-334"><a href="#cb6-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-335"><a href="#cb6-335" aria-hidden="true" tabindex="-1"></a>See the attached Excel file "Factorial design recommended videos" for the video titles and duration.</span>
<span id="cb6-336"><a href="#cb6-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-337"><a href="#cb6-337" aria-hidden="true" tabindex="-1"></a><span class="fu">## Recommended free textbook PDF</span></span>
<span id="cb6-338"><a href="#cb6-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-339"><a href="#cb6-339" aria-hidden="true" tabindex="-1"></a>A free PDF of the text "A First Course in Design and Analysis of Experiments" by Gary Oehlert is available at this website: <span class="ot">&lt;http://users.stat.umn.edu/~gary/Book.html&gt;</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/Stats001/pvalues/edit/main/chapters/ch15-avoid-OVAT.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/Stats001/pvalues/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>